### ISSUE TITLE
Add pep257 into Python checkers

### ISSUE THREAD

**Issue by dunmaksim** [flycheck/flycheck#798] opened 2015-11-18 06:18 UTC
Hello!

Now flycheck (2015-11-17.439 from MELPA) have 3 Python checkers:
* flake8
* pylint
* pycompile

PEP257 is a standard of documentation comments and can work as single package for Python (pep257) or as plugin for flake8 (flake8-pep257), but now flake8-pep257 crash the flycheck with message:

> Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output: Traceback (most recent call last):
> ValueError: I/O operation on closed file

I use Python 3.5, latest flake8-pep257 and EMACS 24.5. Also topic on the [StackExchange](http://emacs.stackexchange.com/questions/18156/how-to-add-pep257-to-flycheck).

Thanks!

**Comment by lunaryorn** [comment] 2015-11-18 09:31
The issue is known, see https://github.com/Robpol86/flake8-pep257/issues/2.  I'd like to wait for some time to see whether the issue gets fixed, before I add another syntax checker.

**Comment by StreakyCobra** [comment] 2015-12-03 09:32
FYI I have this config for enabling `pep257` with the standalone package:

```elisp
(with-eval-after-load 'flycheck
    (flycheck-define-checker python-pep257
                             "A Python syntax and style checker using pep257."
                             :command ("pep257" source)
                             :error-patterns
                             ((warning line-start
                                       (file-name) ":" line " " (one-or-more not-newline) "\n        "
                                       (id (one-or-more (any alpha)) (one-or-more digit)) ": "
                                       (message (one-or-more not-newline))
                                       line-end))
                             :modes python-mode)
    (add-to-list 'flycheck-checkers 'python-pep257)
    (flycheck-add-next-checker 'python-flake8 'python-pylint)
    (flycheck-add-next-checker 'python-pep257 'python-flake8))
```

Note: I'm chaining `flake8`, `pylint` and `pep257` in the last 2 lines. It may not be what you want, just remove these lines in this case.

**Comment by lunaryorn** [comment] 2015-12-03 10:38
The latest release of flake8-pep257 should work fine with Flycheck.  I'm closing this issue now.

**Closed by lunaryorn** 2015-12-03 10:38 UTC
Labels: blocked, feature, waiting for upstream
