### ISSUE TITLE
Flycheck eslint does not respect .eslintignore

### ISSUE THREAD

**Issue by pbgc** [flycheck/flycheck#1392] opened 2018-01-29 22:42 UTC
I have a vue project with .eslintrc.js and .eslintignore on the root of the project.
If I add any .vue file to  .eslintignore .. flycheck keeps using it.

Doing C-c ! C-c I get:

```
-*- mode: compilation; default-directory: "~/Development/projects/pahproject/src/components/" -*-
Compilation started at Mon Jan 29 22:35:15

/Users/pbeck/Development/projects/pahproject/node_modules/.bin/eslint --format\=json --stdin --stdin-filename /Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue < /Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue
[{"filePath":"/Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue","messages":[{"ruleId":"key-spacing","severity":2,"message":"Extra space after key 'newProject'.","line":144,"column":5,"nodeType

```

THE PROBLEM IS WITH:  default-directory: "~/Development/projects/pahproject/src/components/"

If I run the same command on the same directory on the terminal ... I get the same result, BUT If I run the same command on the root of the project (the command is using absolute paths for everything! so no problem!) eslint uses the .eslintignore and gives:

`[{"filePath":"/Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue","messages":[{"fatal":false,"severity":1,"message":"File ignored because of a matching ignore pattern. Use \"--no-ignore\" to override."}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0}]`

The same exact project works with eslint on VSCode and Atom... So I think that eslint should be executed in the root of the project (with the same command) and not in the folder of the file.

* Contents of C-c ! v :

```
Syntax checkers for buffer ProjectList.vue in vue-mode:

  javascript-eslint
    - may enable:  yes
    - executable:  Found at /Users/pbeck/Development/projects/pahproject/node_modules/.bin/eslint
    - config file: found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20180123.1419)
Emacs version:    25.3.1
System:           x86_64-apple-darwin13.4.0
Window system:    ns
```

* Operating system: MacOS 10.13.3
* Emacs Version: 25.3.1
* Flycheck version: 32snapshot (package: 20180123.1419)

**Comment by fmdkdd** [comment] 2018-01-30 10:35
So, if I understand correctly, your `.eslintrc.js` is picked up by `eslint` when you run the command in the subdirectory, but it does not find `.eslintignore`, although both are in the root directory?

**Comment by pbgc** [comment] 2018-01-30 10:52
@fmdkdd Yes. But if I run the command in the root directory both are picked. 
Maybe this is a problem with eslint ... but the question is that flycheck shows problems on ignored files ... and VSCode and Atom don't!
The command is using absolute paths 
`/Users/pbeck/Development/projects/pahproject/node_modules/.bin/eslint --format\=json --stdin --stdin-filename /Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue < /Users/pbeck/Development/projects/pahproject/src/components/ProjectList.vue`
So there is no problem if executed in the root of the project ...

**Comment by fmdkdd** [comment] 2018-01-30 11:03
That does look like an inconsistency with `eslint`, so they might be interested to know about it and maybe fix it.

Otherwise, I agree with you that it probably makes more sense to run the checker in the root project.  To me, it looks like locating the `.eslintrc.js` file should be enough, but I seem to recall it might not be so simple.

@Simplify what's your take on this?

**Comment by Simplify** [comment] 2018-01-30 14:54
@pbgc when file is in `.eslintignore` you should get only warning in Flycheck as in your console output: "File ignored because of a matching ignore pattern. Use \"--no-ignore\" to override.".

We expect that ESLint always finds right configs and don't try to look for it. I'll try to reproduce this during the weekend. If you are inpatient try to add `"--ignore-path" "/path/to/your/.eslintignore"` [after "--format=json" in eslint command](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L8171) and if that helps we should add it as options, maybe even use build-in config search to find that file.

**Comment by pbgc** [comment] 2018-01-30 15:00
@Simplify I think you are not understanding the problem ... (maybe because of my english, sorry) the problem is that Flycheck does not give me that warning! Flycheck gives me the linting errors as if the file was not in the .eslintignore! What you say was what I wanted to happen!
The problem is that eslint is not using the .eslintignore! 
I execute the same command that I get with C-c ! c-c in the command line ... and if I execute with the file folder as base like flyckeck is doing ... I get the same problem .... BUT if I execute the same command in the root of the project ... I get the correct results!
The command is using absolute paths ... so there is no reason why it can+t be executed in the root ...

**Comment by Simplify** [comment] 2018-01-30 15:07
Ok, I see, working directory is needed for ESLint checker. [This PR](https://github.com/flycheck/flycheck/pull/1363) will fix that.

**Comment by pbgc** [comment] 2018-01-30 16:46
@Simplify Yes that PR will fix it indeed ... Sorry bu I could not find it before opening this issue... Any timeframe for the merge of the PR ?
Thanks!

**Comment by fmdkdd** [comment] 2018-02-10 20:35
#1363 has been merged.  @pbgc does updating to the latest Flycheck solve your issue?

**Comment by pbgc** [comment] 2018-02-10 22:09
@fmdkdd YEP! Great news!
from C-c ! C-c:

-*- mode: compilation; default-directory: "~/Development/projects/pahproject/" -*-
Compilation started at Sat Feb 10 22:03:53

/Users/pbeck/Development/projects/pahproject/node_modules/.bin/eslint --format\=json --stdin --stdin-filename /Users/pbeck/Development/projects/pahproject/src/components/TestForm.vue < /Users/pbeck/Development/projects/pahproject/src/components/TestForm.vue
[{"filePath":"/Users/pbeck/Development/projects/pahproject/src/components/TestForm.vue","messages":[{"fatal":false,"severity":1,"message":**"File ignored because of a matching ignore pattern.** Use \"--no-ignore\" to override."}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0}]

Compilation finished at Sat Feb 10 22:03:54

**Comment by cpitclaudel** [comment] 2018-02-11 00:56
@pbgc Thanks a lot for testing so quickly! And thanks for taking the time to report this, and helping make Flycheck better :)

**Closed by cpitclaudel** 2018-02-11 00:56 UTC
