### ISSUE TITLE
How to integrate with per-project Nix environments?

### ISSUE THREAD

**Issue by purcell** [flycheck/flycheck#610] opened 2015-03-21 13:29 UTC
Nix environments let us have tools installed in profiles which can be activated per-project, similarly to how "bundler" isolates a bunch of gems for use together in a ruby project.

`nix-shell` can be used to start a shell inside which all those commands are available, and `nix-shell --command` can be used from "outside" the nix environment to run commands "inside" the environment.

So let's say things like `ghc` or `hlint` are only available inside a per-project nix environment which would normally be accessed using `nix-shell`. 

How can we make sure that the full `hlint` and `ghc` commands which flycheck tries to run in a particular project directory will be wrapped up and passed to `nix-shell --command`?

In `haskell-mode` we provide `haskell-process-wrapper-function` for this purpose:

```
haskell-process-wrapper-function is a variable defined in `haskell-customize.el'.
Its value is identity

  This variable may be risky if used as a file-local variable.

Documentation:
Wrap or transform haskell process commands using this function.

Can be set to a custom function which takes a list of arguments
and returns a possibly-modified list.

The following example function arranges for all haskell process
commands to be started in the current nix-shell environment:

  (lambda (argv) (append (list "nix-shell" "-I" "." "--command" )
                    (list (mapconcat 'identity argv " "))))

See Info Node `(emacs)Directory Variables' for a way to set this option on
a per-project basis.
```

/cc @boothead

**Comment by lunaryorn** [comment] 2015-03-21 15:20
@purcell I could add a similar function to Flycheck, i.e. `flycheck-command-wrapper-function`, which would receive a list with the syntax checker command, and return another list, which would then be used as argument for `call-process`.

Would that be sufficient?  It's not difficult per se, we'd just have to sort out a few minor details, notably, whether the function runs before or after Flycheck's argument substitution.

**Comment by purcell** [comment] 2015-03-21 15:39
Yes, I think that would do the trick. Perhaps @boothead can comment. Also, I believe @jwiegley is using both Nix and Flycheck, so perhaps he'd be kind enough to weigh in on this as a possible integration strategy?

**Comment by jwiegley** [comment] 2015-03-21 18:50
I just start my Emacs from within a `nix-shell`, so I have not solved this problem is any per-project way.

**Comment by lunaryorn** [comment] 2015-03-21 19:11
@purcell Well, let's try this approach then.  It's the easiest to implement in my opinion. Any ideas about the design?  Would you rather like to have the concrete command after substitution, or the "abstract" command as in `:command`?

@jwiegley Is that why you invest so much effort in starting Emacs as fast as possible?

**Comment by jwiegley** [comment] 2015-03-21 19:32
@lunaryorn I actually only start Emacs for the sake of a Nix project maybe once or twice a day.

The reason I want Emacs to start as fast as possible is that during development of Emacs packages (like use-package), I am starting Emacs a few hundreds times a day to test out the loading speed.  So I guess I kind of created the problem I'm trying to solve, but in general I find that while developing tricky Elisp, I'm restarting Emacs perhaps more often than I should; and in those situations, having a fast-loading Emacs is certainly an improvement in quality of life.

**Comment by jwiegley** [comment] 2015-03-21 19:35
I do have it on my back-burner list to solve this per-Nix-project environmental loading, although I have a feeling there will be just too many options to consider.  Because you have:

 - Custom environments introduced by `nix-shell`.
 - Custom environments introduced by `myEnvFun` (perhaps in addition to `nix-shell`).
 - Custom environments introduced by using cabal sandboxing within a nix-shell (I do this for developing on multiple Nix projects that are closely related).
 - Custom environments introduced by using alternate user environments.

Whenever Emacs loads a file, there would need to be a way to inform it (maybe through `.dir-locals`) of all the context it should take into account for that project, in order to produce exactly the right error messages from `flycheck`, `ghci`, etc.

Until now my attempts at this have always led me down rat holes and corner cases that made it both difficult and error prone -- whereas starting Emacs within the "right" shell always works.

**Comment by jwiegley** [comment] 2015-03-21 19:39
In fact, this is really not a Nix-specific problem.  It's that there needs to be a library for Emacs called `context` which goes beyond what `.dir-locals.el` can provide: Dynamic determination of every detail relating to a project on disk.  Maybe this should be a `projectile` add-on, even.  Because we want everything configured:

 - Code layout preferences.
 - Whitespace preferences.
 - Preferred buffer, file and process encodings.
 - `exec-path`
 - `process-environment`
 - File umask (to avoid creating world-readable files in a more "secure" directory)
 - Nix user environment
 - GHC package list
 - Cabal sandbox
 - etc.

It should be something highly customizable for each package, but with sane defaults for discovering what most of these details should be for each project.

**Comment by jwiegley** [comment] 2015-03-21 19:42
Pinging @bbatsov, author of the lovely Projectile.

**Comment by lunaryorn** [comment] 2015-03-22 20:01
@jwiegley Well, I actually think that it *is* a Nix problem.  In my experience, `.dir-locals.el` is usually sufficient, even for large and complex projects, but Nix is special because it's so invasive and wants to control every single aspect of the entire environment, which goes far, far beyond anything that other tools (e.g. virtualenv, cabal sandbox, etc.).

I would rather like to see a specific nix extension, that does one job—exposing a Nix environment to Emacs—and does it well.  This extension would track nix environments for each buffer, and provide the necessary API for other Emacs packages to query information about the Nix environment, which could in turn be used to automatically configure various other Emacs packages accordingly.

**Comment by jwiegley** [comment] 2015-03-23 05:37
Well, outside of Nix I've run into these exact same problems with `hsenv`, for example, and getting `hdevtools` to see exactly the right set of packages relative to my sandboxed environment, rather than my global environment.  In such cases, `.dir-locals.el` was not sufficient.

I think a more general framework for solving this problem would be a better approach, since this problem does exist in other areas.  There are two dimensions that need to be addressed: various classes of details to specialized for each project (see my above list), and the various kinds of systems that can exist at a project level (Nix, hsenv, virtualvm, rvm, etc).

**Comment by lunaryorn** [comment] 2015-04-06 12:12
@jwiegley Well, I don't believe that a generic system will be successful.  There are too many differences between different build system and sandboxing tools, so before long you'll be entangled in all sorts of picky details that take all the fun from such a project.

Personally, I'd like to limit this discussion to the immediate scope of Flycheck.  Regardless of whether you or anyone else manages to implement a generic system such as you devised, it won't be ready any time soon, and meanwhile we should get Flycheck to work with Nix one way or the other.

But, as I said, I don't know Nix, so I'm not the right person to design and implement a solution that works with Flycheck as soon as possible.

**Comment by jwiegley** [comment] 2015-04-06 14:07
@lunaryorn You could well be right, although at the very least a generic project would have a layer that identifies all points of configuration necessary in one place, even if the first version of that project would only ever envision a single backend.

**Comment by lunaryorn** [comment] 2015-04-06 14:18
@jwiegley Well, in my experience successful generic systems evolve from simple systems for a specific purpose, whereas failing generic systems are designed up-front.  But YMMV—my experience is limited and biased and I don't claim to know the ultimate truth :)

If we solve this problem for Flycheck and Nix, and it turns out that it's easily adaptable to other systems like cabal sandboxes or to other Emacs extensions like Company, we can slowly extent to more and more systems and Emacs extensions, whereas if we start the other way around, we are much more likely to make assumptions that don't hold in practice, and consequently impede progress and impose technical debt upon the implementation.

**Comment by jwiegley** [comment] 2015-04-06 14:46
@lunaryorn Hah, fair enough. :)

Here's where my thinking comes from: If you try to architect for the most generic solution, and then implement for a specific solution, you should be able to discover a "sweet spot" in the middle that allows for leaning either toward more generic (to cover more types of systems) or more specific (usually for better performance) -- but the real advantage is that you understand both sides of the problem.  A purely abstract solution does often fail, as you suggest; while purely implementation-driven solutions sometimes miss the forest for the trees.

Maybe the real work does indeed deserve to be done on a flycheck-specific solution, but I hope at least some thought and prototyping could consider how to solve this bugbear once and for all.  I think it has been an issue for Emacs users since the beginning of sandboxing/time.

**Comment by lunaryorn** [comment] 2015-04-06 14:59
@jwiegley Well said, and I cannot but agree :)  The only thing that remains to be discussed is who goes for implementing this solution.  Being no Nix user, I'm afraid that I lack the need and the knowledge, not to mention a notorious lack of time :)

**Comment by jwiegley** [comment] 2015-04-06 15:17
Oh man, I hear you on that lack of time.  I'd love to wrestle with this problem, so I've put it on my list and we'll see if some nimble youngster doesn't beat me to it. :)

**Comment by purcell** [comment] 2015-04-06 15:25
Not to take away from all the things John listed above, I'm primarily interested in how to intercept process creation in a generalised way: similarly to this `nix` discussion, libraries like `ruby-compilation.el` shouldn't have to explicitly deal with all the possible process wrappers (`rbenv`, `rvm`, `bundle exec` etc.) that might be required to run basic commands.

I can imagine a new library like `process-wrap` which would advise (or provide an alternative to) the built-in process-creation functions, and a list of `process-wrap-functions` which are each passed a command line and allowed to amend it.

This would allow handling of scenarios like "Is this executable a ruby script and we're on Windows? Okay, prepend it with 'ruby.exe' because it won't execute on its own."

**Comment by lunaryorn** [comment] 2015-04-06 15:48
@purcell I see your point, but I'm skeptical.  

Process creation is somewhat a core feature of Emacs, which many many libraries rely upon.  I'd not like to see a library that advises these core functions.  It could potentially create a whole lot of issues for other libraries, which would be hard to debug and track down.

Without advises, though, we'd need support from upstream, but I doubt that Emacs upstream would care.  It didn't see the needs of 3rd party Emacs developers in the past, or at least, did not considered them as relevant, and I see not that this attitude is likely to change.  

And I personally find emacs-devel too hostile an environment with too many difficult people for me to discuss this with the Emacs developers.  The less interactions with emacs-devel I need to have, the better.

**Comment by purcell** [comment] 2015-04-06 16:31
I have the same concerns, and it was certainly easier to implement `haskell-process-wrapper-function`. But even putting aside the admittedly-icky idea of using advice for implementation, if there had been a standard way to handle possibly-wrapped command invocations, perhaps that might have been used instead.

**Comment by lunaryorn** [comment] 2015-04-14 18:05
@purcell @jwiegley Do we have any concrete action plan now?  I'd like to know what I'm supposed to do with this issue.  Is there anything that I can implement now to help you with Nix integration?

**Comment by purcell** [comment] 2015-04-15 12:34
My personal inclination would be to provide some sort of `-wrapper-function` option as initially described. Perhaps it would help if I CC'd @ardumont here, since he drove the addition of the `haskell-mode` wrapper function option, and is presumably actively using nix with Emacs?

**Comment by ardumont** [comment] 2015-04-15 14:26
Hello,


> My personal inclination would be to provide some sort of -wrapper-function option as initially described. 

In waiting for someone with a generic solution, +1!

> Perhaps it would help if I CC'd @ardumont here, since he drove the addition of the haskell-mode wrapper function option, and is presumably actively using nix with Emacs?

Yes, I do use nixos/nix and emacs.
But I'm nowhere near having some generic solution.

Regarding the first solution, I think @lunaryorn [got it pretty well in his first description](https://github.com/flycheck/flycheck/issues/610#issuecomment-84371628).

Still, let me know if I can provide anything else.

Cheers,

**Comment by lunaryorn** [comment] 2015-04-15 14:33
Ok, I'll go with `flycheck-substituted-command-wrapper-function`.  It'll allow extensions to transform the command *after* the argument substitution.  IOW, it'll get the command as given to `call-process`, and can do whatever it wants to do with the command.

Would that be sufficient?

**Comment by purcell** [comment] 2015-04-15 14:48
> Would that be sufficient?

Yep, I would think so.

**Comment by lunaryorn** [comment] 2015-04-22 13:52
Closing in favor of #629 then.

**Closed by lunaryorn** 2015-04-22 13:52 UTC
Labels: needs-input, question

**Comment by marcinant** [comment] 2015-05-01 17:33
>The reason I want Emacs to start as fast as possible is that during development of Emacs packages (like use-package), I am starting Emacs a few hundreds times a day to test out the loading speed. So I guess I kind of created the problem I'm trying to solve, but in general I find that while developing tricky Elisp, I'm restarting Emacs perhaps more often than I should; and in those situations, having a fast-loading Emacs is certainly an improvement in quality of life."

@jwiegley Well, why don't you use emacs shell scripts as described (here)[http://nic.ferrier.me.uk/blog/2012_07/emacs-packages-for-programmers] ?

**Comment by jwiegley** [comment] 2015-05-01 18:07
I could probably do something along those lines, but not all testing that I do is worth creating a script to reproduce the actions I take.

**Comment by wedens** [comment] 2015-11-28 18:25
Is there some example on how to use this new variables with NixOS?

**Comment by lunaryorn** [comment] 2015-11-28 18:36
@wedens I think that there is corresponding code in https://github.com/travisbhartwell/nix-emacs/pull/17.  You may also find that package useful; I think it tries to make Emacs work seamlessly on NixOS out of the box.

I'm sorry but I'm not able to give you any more specific guidelines.  I do not use NixOS and do not know what these options need to be set to.  They were contributed by @svenkeidel who may probably be the better person to talk to about this topic.
