### ISSUE TITLE
Add something similar to navigation-minimum-level for the error list

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#698] opened 2015-07-24 17:57 UTC
Hi lunaryorn,

It would be cool to be able to specify a minimum error level for the error list; that would make it easier to deal with checkers that return lots of `info`-level messages.

I expect that implementing this should be a simple patch adding a `defcustom` and a level of filtering to `flycheck-error-list-entries`. If you think this would be a good feature to add, I can make a pull request.

Cheers,
Clément.

**Comment by lunaryorn** [comment] 2015-07-25 16:59
I'd definitely like such a feature, and I'll gladly accept a pull request.  I think that we can learn from Paradox here, which implements filtering for Emacs' package menu.  The error list builds on the same infrastructure—tabulated list mode, that is.

We should also go beyond just a simple defcustom, and add a key binding to filter the error list dynamically.

**Comment by cpitclaudel** [comment] 2015-07-25 19:42
Ok; sounds cool. I looked at paradox's implementation, but it doesn't seem to rely on features of tabulated-mode; instead, it does the filtering by itself.

There are two features here: "hide everything below a certain level", and "show only a specific type of errors". Both seem convenient (though I'd find the former more useful). I'm not sure that they should go on the same key.

I can add a defvar that keeps the current filters; it would be a list of cons cells `(COMPARISON . LEVEL)`, where comparison is a predicate and level is an error level. Then an error `ERR` is displayed only if `(COMPARISON (severity err) (severity level))` is non-nil.

Hiding every error under a certain level `LEVEL` is done by resetting that variable to `'(('>= . LEVEL))`, and showing only one type of error is done by setting it to `'(('= . LEVEL))`. In the future we could also get fancier, for example by setting it to `'(('memq . LEVELS))` to just include certain levels.

What do you think?

**Comment by cpitclaudel** [comment] 2015-07-25 20:17
Btw, we could also require errors to match all cells, instead of one. Or we could simplify this and just allow one cell. Opinions?

**Comment by lunaryorn** [comment] 2015-07-25 20:41
@cpitclaudel I think that this is too complicated.  I think it's sufficient if we add the same filtering like for navigation: Only show errors with a certain level or higher.  To me this seems like _the_ use case for this feature:  First only list errors, fix them, then extend the list to warnings, fix them, and ultimately remove all filters and look at the rest.  I don't think that a user would want to show only warnings, but not errors.  In what situation would that make sense?

**Comment by cpitclaudel** [comment] 2015-07-25 20:49
Agreed in the case of warnings. The idea of selecting a certain level came from the fact that pylint reports TODOs as warnings. One could imagine it reporting them at a custom error level TODO, and then wanting to only see those, for example.

Anyhow, I'm in favor of simplicity too. I'll remove the predicate stuff :)

**Comment by lunaryorn** [comment] 2015-07-28 21:19
@cpitclaudel I'll close this one as duplicate of #701 then :) Thanks for this idea, and for the PR!

**Closed by lunaryorn** 2015-07-28 21:19 UTC
Labels: enhancement
