### ISSUE TITLE
[feature request] flycheck auto disable if file size large than some size.

### ISSUE THREAD

**Issue by zw963** [flycheck/flycheck#1394] opened 2018-02-03 10:37 UTC
Open some big file occasionaly. will cause speed is slow.

e.g. open a big javascript file.

so, i think we can disable it if this file large than 1M, i am not sure `flycheck-before-syntax-check-hook` can do like this.

Thanks.

**Comment by fmdkdd** [comment] 2018-02-03 15:49
Duplicate of #1284.

**Closed by fmdkdd** 2018-02-03 15:49 UTC
Labels: duplicate
