### ISSUE TITLE
glitch at top and bottom of left arrow in fringe double arrows

### ISSUE THREAD

**Issue by tspiteri** [flycheck/flycheck#1741] opened 2020-04-23 16:31 UTC
The bitmap contains two lines `#b10011000`, one for the first and one for the last non-zero entries, but they should be `#b11011000`.

**Comment by cpitclaudel** [comment] 2020-04-23 20:09
It's hard to tell whether this was intended or not, so I'm fine with changing it :) I did that as part of a branch that I'm working on: https://github.com/flycheck/flycheck/pull/1742

Do you want to give it a try, btw? I'm adding support for showing indicators in the margins instead of the fringe.

**Comment by tspiteri** [comment] 2020-04-23 23:56
Thanks! I'm going to stick to the fringes though, I have just spent quite a bit of time earlier today making the fringe look good for me on HiDPI by creating larger bitmaps of all vanilla Emacs bitmaps, the flycheck bitmap, and the magit bitmaps, and now I'm not going to change to margins :) I only saw the glitch when I was drawing a 16x16 version of the width-8 flycheck bitmap.

(On my system I just assume I know whether it is HiDPI so I don't have any HiDPI smart detection. On my non-HiDPI system I just don't require the bitmap modifying file.)

**Comment by cpitclaudel** [comment] 2020-04-24 04:06
> Thanks! I'm going to stick to the fringes though, I have just spent quite a bit of time earlier today making the fringe look good for me on HiDPI

That sounds great.  Maybe you'd like to pick up the stalled PR at https://github.com/flycheck/flycheck/pull/1553 ? ;)

**Comment by tspiteri** [comment] 2020-04-24 11:56
I actually did have a look at #1553, but the comments there talk about detecting HiDPI support. I even dug up the emacs-devel thread mentioned there, and in that thread there was even talk about moving a frame across monitors with different resolutions dynamically. What I did is nothing of the sort: on machines I know I always use in HiDPI mode I change the bitmaps, while on others I don't change the bitmaps.

A hack that could work that I just thought of: flycheck could detect on startup whether `(frame-parameter nil 'left-fringe)` is 16, and if it is 16 then it sets the bitmap to a larger version. This would probably not cause any issues, as it only means that people who themselves customized their fringe to be 16 pixels wide get the hi-res version. I could implement that, but not anything more complex.

**Comment by cpitclaudel** [comment] 2020-04-24 14:20
> A hack that could work that I just thought of: flycheck could detect on startup whether (frame-parameter nil 'left-fringe) is 16, and if it is 16 then it sets the bitmap to a larger version.

That's a great idea, actually! :)  I think we could detect it in `flycheck-error-level-fringe-bitmap`, though; and we should call `window-fringes`, since the fringes are can be customized at the buffer level too.  I imagine something along these lines would work?

* Change `flycheck-define-error-level` so the `:fringe-bitmap` argument accepts a cons of two bitmaps (at first I thought we should take an arbitrary list, but fringes are capped at 16px, so there's no point to take a larger image than that).
* Change `flycheck-error-level-fringe-bitmap` to return the car of that cons, or the cdr if an extra optional `high-dpi` argument is non-nil
* Change `flycheck-error-level-make-fringe-icon` to pass the extra `high-dpi` argument depending on the value of `window-margins`.

WDYT?

**Comment by tspiteri** [comment] 2020-04-25 12:29
@cpitclaudel #1744 includes this tweak.

On another note, in #1744 you added a commit that renames `'flycheck-fringe-bitmaps-double-arrow` to `'flycheck-fringe-bitmaps`. This affects external code, for example lsp-mode has [this code](https://github.com/emacs-lsp/lsp-mode/blob/f1d2cc0311d5995bf7cdeb583cdc587c21308b2c/lsp-mode.el#L7689-L7695)
```el
          (flycheck-define-error-level new-level
            :severity (get flycheck-level 'flycheck-error-severity)
            :compilation-level (get flycheck-level 'flycheck-compilation-level)
            :overlay-category category
            :fringe-bitmap (get flycheck-level 'flycheck-fringe-bitmap-double-arrow)
            :fringe-face (get flycheck-level 'flycheck-fringe-face)
            :error-list-face face)
```
which now breaks as the new levels created by lsp-mode do not have a fringe symbol. Is this breakage intentional? That is, will this be reverted or should I for example file a bug report/pull request with lsp-mode?

**Comment by cpitclaudel** [comment] 2020-04-25 13:07
Ouch, thanks.  Fixed in https://github.com/flycheck/flycheck/pull/1747; can you have a look?

**Closed** 2020-04-25 23:17 UTC
Labels: kind: bug, status: has pr
