### ISSUE TITLE
flycheck hangs with eslint

### ISSUE THREAD

**Issue by brunoqc** [flycheck/flycheck#794] opened 2015-11-16 16:01 UTC
I have 80 errors in my file if I run eslint from the command line. I tested with a smaller file (with less errors) and it was fine. Emacs has 0% cpu usage and I don't see eslint in the process manager. I think it's related to eslint since the file opens if I remove eslint from my PATH.

There's nothing in the message buffer.

GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

**Comment by lunaryorn** [comment] 2015-11-16 16:46
Please tell us your Flycheck version `M-x flycheck-version` and your eslint version, and please check whether you are able to reproduce the issue in `emacs -Q`.

**Comment by brunoqc** [comment] 2015-11-16 16:51
Flycheck version: 0.25snapshot (package: 20151113.858)
eslint v1.9.0
node v5.0.0

I can't reproduce with `emacs -Q`.

**Comment by lunaryorn** [comment] 2015-11-16 16:53
In other words, if you start `emacs -Q`, enable `global-flycheck-mode` and visit the affected file Flycheck works fine and highlights all issues in the file?

**Comment by brunoqc** [comment] 2015-11-16 17:07
Sorry I didn't realise you wanted me to load flycheck manually.

emacs hangs when I visit the affected file after loading flycheck manually like this :

```lisp
(add-to-list 'load-path "~/.emacs.d/elpa/dash-20151021.113")
(add-to-list 'load-path "~/.emacs.d/elpa/flycheck-20151113.858")
(require 'flycheck)
(global-flycheck-mode)
```

**Comment by lunaryorn** [comment] 2015-11-16 17:12
@brunoqc Uhm, yes, I wanted you to actually try and see whether Flycheck works in `emacs -Q`.  Sorry for the confusion.

Can you given me the file which shows this issue?  I'd like to try myself.  Alternatively, can you try to reproduce the problem on a Unix system?  That's somewhat crucial, for otherwise I'm unable to debug and fix the issue.  If it's a Windows-only problem, you'll have to debug that yourself.

Besides, you're not using the latest Flycheck build from MELPA, please consider updating.

**Comment by brunoqc** [comment] 2015-11-16 18:23
I have the problem with https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js . I also tested with an up-to-date flycheck.

I wasn't able to reproduce on Debian.
```
Debian GNU/Linux 8.2 (jessie)
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.4) of 2015-06-28 on trouble, modified by Debian
Flycheck version: 0.26snapshot (package: 20151116.124)
eslint v1.9.0
node v5.0.0
```

I'll test at home later today on a faster and better Windows machine.

**Comment by brunoqc** [comment] 2015-11-17 01:14
I also have the problem at home.

**Comment by lunaryorn** [comment] 2015-11-17 07:47
Also on a Windows machine?  I'm inclined to believe that it's s Windows specific issue.  Then you're on your own.  

I'm sorry but I can't and don't want to fix Windows issues.  I don't have access to a Windows development machine and it's too alien to me to spend a lot of time with.

Sorry.

**Comment by lunaryorn** [comment] 2015-11-17 12:52
@brunoqc I'm also unable to reproduce this issue on a Linux system. I'm sorry.

**Comment by brunoqc** [comment] 2015-11-17 19:00
> Also on a Windows machine?

Yes.

> I'm sorry but I can't and don't want to fix Windows issues.

No problem.

I checked around a bit even if I don't know lisp (or is it elisp?) and I have a workaround that work for me in case anyone else has the same problem.

It works if flycheck call this Go program which only call eslint. It's weird that it doesn't work with `cmd.Stdin = os.Stdin`.

I'll check again another day.

```lisp
:command ("my.exe" "eslint" "--format=checkstyle"
```

```go
package main

import (
	"io"
	"os"
	"os/exec"
)

func runCMD() error {
	cmd := exec.Command(os.Args[1], os.Args[2:]...)
	// cmd.Stdin = os.Stdin // doesn't work
	cmd.Stdout = os.Stdout

	pipe, errPipe := cmd.StdinPipe()
	if errPipe != nil {
		return errPipe
	}

	if err := cmd.Start(); err != nil {
		return err
	}

	if _, err := io.Copy(pipe, os.Stdin); err != nil {
		return err
	}

	if err := pipe.Close(); err != nil {
		return err
	}

	cmd.Wait() // ignore the return code

	return nil
}

func main() {
	err := runCMD()
	if err != nil {
		panic(err)
	}
}
```

**Comment by lunaryorn** [comment] 2015-11-17 19:05
@brunoqc You're not using cygwin, are you?

**Comment by brunoqc** [comment] 2015-11-17 19:09
I have it installed but I don't use it. It's not in my path. I may have some gnu .exe like sh.exe in my path.

**Comment by lunaryorn** [comment] 2015-11-17 19:22
I'm at a loss then.  I've no clue what could possibly cause this issue.  My Windows foo is pretty bad, though.

Out of curiosity: Could you try another Javascript checker, e.g. `jshint` or `standard`?  And if those hang too, could you try some other checker from Flycheck?  Doesn't matter what language or what tool, but it should have `:standard-input t`, because that is what changed of late.

**Comment by brunoqc** [comment] 2015-11-17 19:43
`jshint` did hang but not gofmt and flake8.

**Comment by lunaryorn** [comment] 2015-11-17 19:45
Well, that's smells like a Node on Windows issue then.  Is there a known issue about standard input on Windows or something like that?

**Comment by brunoqc** [comment] 2015-11-17 19:49
> Is there a known issue about standard input on Windows or something like that?

I have no idea.

**Comment by Dogfalo** [comment] 2015-11-30 06:35
@brunoqc, I would try using an older version of flycheck, I also encountered the same problem but my old version `flycheck-20150921.947` worked fine.

**Comment by cpitclaudel** [comment] 2015-11-30 12:04
I might be able to look at this quickly on a Windows machine. @Dogfalo @brunoqc Which version of the OS were you using?

**Comment by Dogfalo** [comment] 2015-11-30 14:46
I am on windows 10 and emacs 24.4

**Comment by brunoqc** [comment] 2015-11-30 16:05
Windows 10
Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

**Comment by Xeveo** [comment] 2015-12-17 02:51
I'm having the same issue (Windows 7 and emacs 24.5.1)

---
I used git bisect to find the commit where the issue was introduced:
##### Oct 25 - 6088731a82b672eae9372c3e6765899382c4e3f2 - Use standard input for javascript checkers.

I'm a newbie when it comes to elisp, so I'm afraid I won't be of much use to actually suggest a fix... but at the very least, we've narrowed it down to a few small changes made in a single commit.

Hopefully there haven't been too many changes since then that rely on this commit, and fixing it will be easy.

In the mean time, anyone else having this problem can checkout c2e413ad535e1c7b1403a54679f2d1b5cded50bc. That's the latest commit that should be working correctly on Windows.

**Comment by cpitclaudel** [comment] 2015-12-17 03:18
Hi Xeveo,

Thanks for bisecting; I haven't gotten around testing this yet. I think @lunaryorn identified this problem in a previous message, mentioning stdin checkers. A fix will certainly not be very easy, depending on the extent of the problem.

As a workaround, you could just copy the checker definition from that commit, instead of reverting to a previous commit. The issue seems to be with the way the checkers in question deal with being fed input on standard input instead of as a separate file.

**Comment by Xeveo** [comment] 2015-12-17 05:13
@cpitclaudel

Thank you for the quick response. As you and @lunaryorn suggested, the issue seems to be a problem with standard-input.

Reverting the relevant changes from the commit I mentioned fixes the issue.
I've forked, branched from master, and committed the change, and all seems to be well.
[8b472e5 - Standard Input Revert](https://github.com/Xeveo/flycheck/commit/8b472e52ce4ad82158e4aaf49dc8d6eedc70923f)

I don't want to create a pull request, because I'm really not familiar with the code, and as I said in my previous comment, I'm very new to the language. Besides, the changes in 6088731a82b672eae9372c3e6765899382c4e3f2 were made for a reason. If it works on Unix/Linux systems, then there's probably an alternate solution that would be more appropriate than reverting.

**Comment by bschwehn** [comment] 2015-12-21 22:35
Just wanted to comment, that I had the same issue on my windows machine (working fine on my linux systems) and the patch by Xeveo seems to have solved my issue.

**Comment by wsw0108** [comment] 2015-12-28 03:03
@brunoqc I had the same problem, but with jshint.cmd.

And I found that if the length of buffer/file less than or equals to 4096 bytes, jshint works fine, otherwise jshint hangs emacs...

I guess this caused by write() in mingw-msys that build emacs.

https://github.com/flycheck/flycheck/blob/master/flycheck.el#L4631
https://github.com/emacs-mirror/emacs/blob/master/src/process.c#L5796
https://github.com/emacs-mirror/emacs/blob/master/src/sysdep.c#L2421
https://github.com/emacs-mirror/emacs/blob/master/src/sysdep.c#L2386

**Comment by baerrach** [comment] 2016-01-07 02:42
I started investigating this, and eventually found this bug by searching for 4096 in one of my queries. The link provided by @Xeveo has resolved the issue.

Having found what will cause the problem, but not what actually causes the problem, and a valid workaround, I will live with the workaround.

If its possible to include this problem in the documentation that would be helpful.

**Comment by lunaryorn** [comment] 2016-01-07 11:01
@baerrach I am sorry, but as said before we do not support Windows.  As such, please understand that we do not want to document Windows-specific bugs and issues in our documentation. 

I do not think that reverting a particular commit in Flycheck is a good workaround anyway.  It doesn't really work when installing from ELPA—which is the only supported installation method for Flycheck—and sooner or later it'll become impossible without conflicts.

I'm sorry, but documenting an issue in an unsupported OS where the only known workaround is to revert commits in Flycheck is not an option for us.

**Comment by baerrach** [comment] 2016-01-07 11:23
I understand, I have seen the notice of non-support for Windows.

But it does work from melpa - at least when not using stdin. I have it working. 

I just want some trail left behind for other people to be able to find so they can get it working too.

**Comment by brunoqc** [comment] 2016-01-07 15:22
> I just want some trail left behind for other people to be able to find so they can get it working too.

A note in the README pointing to this issue would be nice.

This problem is a big deal on Windows. I'm surprised so few people use flycheck on Windows.

**Comment by Xeveo** [comment] 2016-01-07 16:25
At a minimum, I agree that a note in the readme pointing to this issue would be nice.

An even better outcome would be the introduction of a variable that lets us disable the use of standard input. I'm not sure if that's viable, given the long-term plans for flycheck; but, that would give those of us who want/need to use Windows the option to use this package out of the box.

I'm sure there are plenty of people who _want_ to use flycheck on Windows, but for every one of us who has found this issue and worked around it, there are many others who simply quit in frustration.

**Comment by lunaryorn** [comment] 2016-01-07 18:38
@Xeveo We will not make standard input support customisable.  Please take a look at the number of commits and the amount of changes related to this feature; making standard input support customisable is too much effort to fix an issue on an operating system that we do not support.  I'm sorry.

The only way forward for this issue is that someone with Windows and Emacs knowledge comes up with a proper fix or a minimally invasive workaround that we can add to Flycheck itself.  Meanwhile I'd recommend that you override the definitions of affected syntax checkers in your configuration with their definitions from before.

**Comment by Xeveo** [comment] 2016-01-07 18:40
@lunaryorn 
I knew it was a big ask. Just thought I'd throw it out there.

**Comment by lunaryorn** [comment] 2016-01-07 20:27
@Xeveo @brunoqc @baerrach I've re-opened this issue, and as a compromise, I [added links to the list of known open Windows issues](https://github.com/flycheck/flycheck/commit/78bf29bc061292537cdf6258ce193e472a72dd8f) to the README and to the manual.  I hope that this notice is sufficient; I'll not go so far as to link individual issues.

We'll now track Windows-specific issues under the new `B-Windows only` label (`B` is for "blocked", i.e. issues that we can't work on currently). These issues will almost always move straight to the (also new) `S-needs your love` column of our board, i.e. we won't do anything about them unless someone else steps up to help, or the bug is really really bad (bad as in "makes Emacs explode your computer screen when you load Flycheck" :sunglasses:).

I hope that's ok to you; we really can't do anything about Windows, and I for my part am not willing to make compromises about the feature set that we use on supported systems (e.g. Linux, BSD, OS X) to maintain a flawless Windows experience.

**Comment by baerrach** [comment] 2016-01-07 21:40
Linking to the known Windows issues is a great compromise, and an incentive for someone to try fixing them :)

Cheers

**Comment by cpitclaudel** [comment] 2016-01-11 06:03
Alright, I have a [cause](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L4651), an [Emacs bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22344), and a fix :)

In short: this is an Emacs issue, and it's not related to node. I have no idea why Emacs has this bug, but I found a minimally intrusive [workaround](https://github.com/flycheck/flycheck/commit/cebe9d28b60bac9191a9239bf748b37662a5b601).

@brunoqc and other people who reproduced this bug, could you please try out the `fix-794` branch? It's at https://github.com/flycheck/flycheck/tree/fix-794 . Alternatively, you can test the change using the usual Flycheck from MELPA by adding the following to your .emacs and restarting Emacs:

```elisp
(require 'flycheck)


(defun flycheck-start-command-checker (checker callback)
  "Start a command CHECKER with CALLBACK."
  (let (process)
    (condition-case err
        (let* ((program (flycheck-find-checker-executable checker))
               (args (flycheck-checker-substituted-arguments checker))
               (command (funcall flycheck-command-wrapper-function
                                 (cons program args)))
               ;; Use pipes to receive output from the syntax checker.  They are
               ;; more efficient and more robust than PTYs, which Emacs uses by
               ;; default, and since we don't need any job control features, we
               ;; can easily use pipes.
               (process-connection-type nil))
          ;; We pass do not associate the process with any buffer, by
          ;; passing nil for the BUFFER argument of `start-process'.
          ;; Instead, we just remember the buffer being checked in a
          ;; process property (see below).  This neatly avoids all
          ;; side-effects implied by attached a process to a buffer, which
          ;; may cause conflicts with other packages.
          ;;
          ;; See https://github.com/flycheck/flycheck/issues/298 for an
          ;; example for such a conflict.
          (setq process (apply 'start-process (format "flycheck-%s" checker)
                               nil command))
          (setf (process-sentinel process) #'flycheck-handle-signal)
          (setf (process-filter process) #'flycheck-receive-checker-output)
          (set-process-query-on-exit-flag process nil)
          ;; Remember the syntax checker, the buffer and the callback
          (process-put process 'flycheck-checker checker)
          (process-put process 'flycheck-callback callback)
          (process-put process 'flycheck-buffer (current-buffer))
          ;; Track the temporaries created by argument substitution in the
          ;; process itself, to get rid of the global state ASAP.
          (process-put process 'flycheck-temporaries flycheck-temporaries)
          (setq flycheck-temporaries nil)
          ;; Send the buffer to the process on standard input, if enabled
          (when (flycheck-checker-get checker 'standard-input)
            (save-excursion
              (save-restriction
                (widen)
                (goto-char (point-min))
                (while (not (eobp))
                  (let ((from (point)))
                    (forward-char (min 50 (- (point-max) (point))))
                    (process-send-region process from (point))))
                (process-send-eof process))))
          ;; Return the process
          process)
      (error
       ;; In case of error, clean up our resources, and report the error back to
       ;; Flycheck
       (flycheck-safe-delete-temporaries)
       (when process
         ;; No need to explicitly delete the temporary files of the process,
         ;; because deleting runs the sentinel, which will delete them anyway.
         (delete-process process))
       (signal (car err) (cdr err))))))
```

Hopefully this fixes the issue; it does for me, but I don't use Windows heavily, so confirmation would be good :)

**Comment by Xeveo** [comment] 2016-01-11 06:44
@cpitclaudel 
I can confirm that the fix-794 branch fixes the issue.

**Comment by cpitclaudel** [comment] 2016-01-11 06:56
Yay! Thanks for testing @Xeveo :)

**Comment by baerrach** [comment] 2016-01-11 07:13
@cpitclaudel
Likewise I can confirm that the fix-794 branch fixes the issue.

**Comment by kimgronqvist** [comment] 2016-01-11 09:13
Just wanted to chime in and say that my issues with jshint on Windows 8 was helped by the fix.

**Comment by lunaryorn** [comment] 2016-01-11 09:58
These are great news!  We will definitely add this workaround to Flycheck, after some polishing.  Thank you all very much for reporting and testing the fix, and for your patience!

@cpitclaudel Would you mind to create a PR for us to discuss the implementation details?  Specifically I'd like to apply this fix only on Windows systems; on UNIX we should still send everything at once and rely on Emacs' internal buffering which is likely much faster.

Also, thank you very much for debugging and fixing this issue.  That's awesome work! 🎆👍

**Comment by brunoqc** [comment] 2016-01-11 14:05
@cpitclaudel 
The `fix-794` branch also fixes the issue for me.
Merci.

**Comment by cpitclaudel** [comment] 2016-01-11 15:51
Thanks for testing @brunoqc :) I've renamed the branch to `794-chunked-stdin-on-windows` and created the PR at #850. I'm still curious to see how the bug-gnu-emacs thread will go.

**Comment by lunaryorn** [comment] 2016-01-13 15:50
Thank you all very much for your help with tracking down the cause, and for your thorough testing of the fix.  We appreciate your help, and a very happy to work with such great people!  Thank you very much.

I'd like to inform you that following @cpitclaudel's bug report to Emacs upstream a [potential fix for this issue](http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-25&id=58a622d473112f8ff5b4bdb3e49bc6573dfd3404) was [committed to the `emacs-25` branch](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22344#47) (thank you very much, Eli!).

If you have some time to spare, and would like to help Emacs and Flycheck, it would be awesome if you could compile the latest `emacs-25` including commit `58a622d` on Windows and test whether the issue still persists with the current Flycheck version.  It'd help us very much if we could confirm that the fix does indeed fix the issue on Emacs' side.

Thank you very much.

**Comment by bschwehn** [comment] 2016-01-13 20:21
I can no longer reproduce the hang using a build  that includes 58a622d, so it looks to me that the issue is fixed. 

Thanks
Ben

**Comment by brunoqc** [comment] 2016-01-13 20:23
@bschwehn Do you have instructions how to build emacs on Windows or did you use a snapshot from somewhere?

**Comment by bschwehn** [comment] 2016-01-13 20:32
@brunoqc I used the instructions from here: 

http://sourceforge.net/p/emacsbinw64/wiki/Build%20guideline%20for%20MSYS2-MinGW-w64%20system/

Also in the source tree, the nt folder has some instructions. I had no issues (but make sure to have autocrlf turned off when checking out emacs, not working otherwise). 

Just to make clear: I have so far not actually tried flycheck, just the hang repro steps in the bug report. 

I was able to repro the hang using the steps that Clément described in the emacs bug report and can no longer repro using my latest build. 

I will try with flycheck tomorrow.

**Comment by bschwehn** [comment] 2016-01-13 20:46
Also, if it helps anyone, I can put the build up somewhere. Let me know.

**Comment by Xeveo** [comment] 2016-01-13 21:08
I can also confirm that the issue seems to be fixed by the `58a622d` commit.

**Comment by bschwehn** [comment] 2016-01-13 21:19
@Xeveo: did you  try with actually using flycheck in a scenario where it hanged before (undoing any workarounds you have applied)? I didn't have time to look at it further yet, but noticed that with the workarounds still in place (i.e. flycheck is passed a file, not via stdin), flycheck still works, but I get a new warning message like: 

    Suspicious state from syntax checker javascript-jshint: Checker javascript-jshint returned non-zero exit code 2, but no errors from output: <?xml version="1.0" encoding="utf-8"?>
    <checkstyle version="4.3">
    	<file name="c:/Users/BENJAM~1.SCH/AppData/Local/Temp/flycheck31856JJr/app.routes.js">
    		<error line="316" column="13" severity="warning" message="&apos;logger&apos; is not defined." source="jshint.W117" />
    		<error line="18" column="17" severity="warning" message="&apos;log&apos; is defined but never used." source="jshint.W098" />
    	</file>
    </checkstyle>
    Checker definition probably flawed.


Which I did not get before. Did you notice anything like this also? I don't think it is related to the 58a622d commit.

**Comment by Xeveo** [comment] 2016-01-13 21:28
I checked out the lastest master content for flycheck, and opened a file that had previously caused emacs to hang (20,480 bytes in size). The file was linted correctly, and I did not get any warnings or errors from emacs.

I've tested with both javascript-jshint, and javascript-eslint.

**Comment by brunoqc** [comment] 2016-01-13 22:31
@bschwehn
Thanks for the instructions.

It seems I still have the problem even with the 58a622d473112f8ff5b4bdb3e49bc6573dfd3404 commit.

I'm leaving work for today. I'll test again tomorrow.

**Comment by cpitclaudel** [comment] 2016-01-14 00:50
I've had a bit of time to recompile Emacs on Wdinows. The results of my tests were that a plain build (according to the instructions in nt/INSTALL) of the master branch does fail (as expected), but a build of the emacs-25 branch seems to work as expected.

**Comment by lunaryorn** [comment] 2016-01-14 10:19
Thank you all for your time spent on testing the fix.  You're awesome people, the lot of you :heart_eyes: :clap:

I'll commit the workaround for Emacs 24 as soon as possible.  

In order to correctly enable the workaround for all affected versions of Emacs and operating systems, I'd like to ask one final question, though:

Did any of you observe the issue on cygwin?  Or could anyone test whether cygwin is also affected?

**Comment by brunoqc** [comment] 2016-01-14 15:49
Disregard my last comment. I was on the wrong branch. Sorry about that.

The `emacs-25` branch does fix the problem I had with eslint.

**Comment by brunoqc** [comment] 2016-01-14 16:50
> Did any of you observe the issue on cygwin? Or could anyone test whether cygwin is also affected?

I'm trying to test with cygwin but flycheck doesn't show the eslint errors.

```
  javascript-eslint
    - predicate:  t
    - executable: Found at /cygdrive/c/Users/bbigras/AppData/Roaming/npm/eslint
```

I wonder if it's because I'm using a non-cygwin node.js. eslint seems to work in the Cygwin64 Terminal.

node.js doesn't seem to be available as a cygwin package.

**Comment by cpitclaudel** [comment] 2016-01-14 18:28
Indeed, I had trouble trying this with Cygwin as well; node.js was confused by the path format for the config file (`/cygdrive/...`). Since the Emacs patch that fixed this issue will apply to Cygwin as well I'm not too too worried.

I opened an issue with the Node.js people, to get their input. We'll push the temporary fix to Flycheck soon, and the problem will be definitively fixed with the next release of Emacs. Phew.

**Closed** 2016-01-14 21:32 UTC
Labels: B-waiting for feedback, B-Windows only, K-bug, P-critical, S-in progress

**Comment by lunaryorn** [comment] 2016-01-14 21:35
I merged @cpitclaudel's fix into `master`; it should be in the next MELPA build.  Thank you very very much for your help and your patience.
