### ISSUE TITLE
Flycheck error opens in a new frame when neotree is open

### ISSUE THREAD

**Issue by chris-martin** [flycheck/flycheck#938] opened 2016-04-03 01:13 UTC
I'm still pretty new to emacs, so I don't know whether this is the right project for this ticket, or if I just did something wrong.

When I have neotree open, instead of just opening a new window to the right or bottom, flycheck opens a whole new frame instead.

![screenshot from 2016-04-02 18-10-44](https://cloud.githubusercontent.com/assets/399718/14230075/7f4ee5cc-f8fe-11e5-9eb6-c5c64590b3c5.png)

Obviously this seems like pretty screwed-up behavior, as it covers up the buffer I'm editing and steals focus.

**Comment by cpitclaudel** [comment] 2016-04-03 09:47
Hi Chris,

This looks weird, and it's probably not Flycheck specific (Flycheck lets Emacs decide where to open new Emacs windows in most (all?) cases). 
Still, can you post that sample of code? My hunch is that in only occurs with large error messages, right?

**Comment by chris-martin** [comment] 2016-04-03 10:20
You can reproduce it with any multi-line message (which is any error message in Haskell).

What does flycheck call to open the window? Maybe I can track it down from there.

**Comment by cpitclaudel** [comment] 2016-04-03 11:03
> You can reproduce it with any multi-line message (which is any error message in Haskell).

No, not really. When the message is short enough flycheck prints it in the minibuffer for me:

![screenshot from 2016-04-03 13 00 30](https://cloud.githubusercontent.com/assets/8181630/14232074/13d0df5a-f99c-11e5-8d82-68f265e9c05c.png)

Flycheck the function in `flycheck-display-errors-function`, which usually is `flycheck-display-error-messages`, which in turn calls `display-message-or-buffer`. Looking at neotree, it seems that it strongly dedicates its own window, which might explain why a new frame is popping up.

**Comment by lunaryorn** [comment] 2016-04-03 11:27
@chris-martin Thank for reporting this issue.  I must admit that it looks really strange; I've never seen this before.  May we take a look at your Emacs configuration?  And could you perhaps tell us the dimensions of your Emacs frame? And probably experiment whether the issue persists of you are using a larger frame, probably on a larger screen as well, if possible?

At least please also include a bit of information about your system: Emacs version, Flycheck version, your OS, etc. In doubt include include more than less: This issue seems so obscure to me that every single bit of information could help.

@cpitclaudel Thank you for taking care and for trying to reproduce.  I hope that this one is a simple one ultimately, and not that deep as the last obscure thing you took (the Windows stdin issue) ☺️😇

**Comment by cpitclaudel** [comment] 2016-04-03 11:36
Indeed, that info would be very useful!

My guess for now is that `display-message-or-buffer` somehow decides that it would be a good idea to reuse the neotree window, but then trying to display something in it fails (since that window is dedicated to the neotree buffer), and so a new window opens. I need to think about how to fix that; in any case it will be much easier once I have a repro :)

**Comment by chris-martin** [comment] 2016-04-03 22:28
> No, not really. When the message is short enough flycheck prints it in the minibuffer for me:

Sorry, I guess it does have to be more than a few lines.

> which in turn calls `display-message-or-buffer`

[`display-message-or-buffer`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Displaying-Messages.html) docs:

> This function displays the message message, which may be either a string or a buffer. If it is shorter than the maximum height of the echo area, as defined by `max-mini-window-height`, it is displayed in the echo area, using message. Otherwise, `display-buffer` is used to show it in a pop-up buffer.

[`display-buffer`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html#Window-Choice) docs:

> If all the above methods fail for whatever reason, create a new frame and display the buffer there.

**Comment by chris-martin** [comment] 2016-04-03 22:35
My entire Emacs and NixOS configurations are published in my [home directory repo](https://github.com/chris-martin/home).

The frame size is 187 x 48.

**Comment by chris-martin** [comment] 2016-04-03 22:55
Here's a small project that you can reproduce on: https://github.com/chris-martin/haskell-sandbox/tree/flycheck-938 - The last commit introduces an error that's 13 lines long.

**Comment by chris-martin** [comment] 2016-04-03 22:59
Testing with larger frame sizes, it looks like the width of the frame is irrelevant, only the height. If the frame isn't tall enough and it decides to do a horizontal split, it pops up a new frame when neotree is present regardless of the frame width.

**Comment by chris-martin** [comment] 2016-04-03 23:41
If I eval `(switch-to-buffer-other-window "*Messages*")` with neotree open, the message buffer opens in a new frame. So it doesn't look like this has much to do with flycheck anymore - the issue is with neotree, or emacs itself?

**Comment by lunaryorn** [comment] 2016-04-04 07:28
@chris-martin I must admit that I do not know where this issue comes from.

It's surely not a specific issue with Flycheck, simply because Flycheck doesn't do any unusual things with windows.  We don't add any display rules that'd cause frames to pop up under normal circumstances.

That leaves you with three possible causes: Your Emacs configuration, neotree and Emacs itself.  I'd recommend that you start narrowing down this list, by trying to [reproduce the issue in `emacs -Q`](http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html).  Start `emacs -Q`, manually load and turn on Neotree and then check whether you can reproduce the issue.  If you can, your Emacs configuration is likely not the cause.

At a wild guess, I'd attribute the breakage to neotree.  I've taken a quick look at its source, and found that it manages its window explicitly and advises window primitives which is at least unusual, and probably forces Emacs into a state where it can't find a split window anymore.  I think you should rise this issue with neotree.

In any case, I'm closing this issue as invalid, as it has turned out to be unrelated to Flycheck.  Thank you very much for debugging the issue.

**Closed by lunaryorn** 2016-04-04 07:28 UTC
Labels: B-needs to be reproduced, K-bug
