### ISSUE TITLE
go-vet seems temporary switch current buffer to another buffer.

### ISSUE THREAD

**Issue by hex2010** [flycheck/flycheck#1076] opened 2016-09-09 13:02 UTC
The checker `go-vet` seems temporary switch current buffer to another (previous) buffer, and then switch back immediately, without visible effect,  but trigger the `buffer-list-update-hook`, which may confuse other code. 

* What you did, and what you expected to happen instead
  
  I'd like to avoid `buffer-list-update` during editing golang source file, with `go-vet` checker enabled.

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]
  
  I don't want to reproduce the issue in `emacs -Q`, but in my normal emacs environment, it can always reproduce:

 1. install and enable `flycheck`, ensure `go-vet` is enabled.
 1.  hook up `buffer-list-update-hook` to `(message (prin1-to-string (current-buffer)))`
 1. open and edit a golang source file (in my case any *.go file), modify some statement.
 1. switch to the `*Messages*` buffer, find out something like this:
  ```
#<buffer *scratch*>
#<buffer tinymail.go>
#<buffer *scratch*>
#<buffer tinymail.go>
#<buffer *scratch*>
#<buffer tinymail.go>
#<buffer *scratch*>
#<buffer tinymail.go>
#<buffer *scratch*>
#<buffer tinymail.go>
#<buffer *scratch*>
#<buffer tinymail.go>
...
  ```

 If I add `go-vet` to the `flycheck-disabled-checkers` list,  save for further sessions, then the BUG got "fixed".

* Your Flycheck setup from `M-x flycheck-verify-setup`

```
Syntax checkers for buffer sendmail.go in go-mode:

  go-gofmt
    - predicate:  t
    - executable: Found at /Users/cct/go/bin/gofmt

  go-golint
    - predicate:  t
    - executable: Found at /Users/cct/bin/golint

  go-vet (disabled)
    - predicate:   t
    - executable:  Found at /Users/cct/go/bin/go
    - go tool vet: present

  go-build
    - predicate:  t
    - executable: Found at /Users/cct/go/bin/go

  go-test
    - predicate:  nil
    - executable: Found at /Users/cct/go/bin/go

  go-errcheck
    - predicate:  t
    - executable: Found at /Users/cct/bin/errcheck

  go-unconvert
    - predicate:  nil
    - executable: Not found


The following syntax checkers are not registered:

  - swift

Try adding these syntax checkers to `flycheck-checkers'.  Flycheck
Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 30snapshot (package: 20160904.1622)
Emacs version:    25.1.50.1
System:           x86_64-apple-darwin15.6.0
Window system:    ns

```

**Comment by lunaryorn** [comment] 2016-09-09 13:43
Thank you for reporting this issue. I'm afraid though that you reproducing this issue in `emacs -Q` is quite mandatory for us to address this issue.  I can't help but wonder about your attitude: You don't want to reproduce the issue in `emacs -Q`, yet you want us to address the issue?

In any case I think that switching buffers is a normal operation for Emacs, even within non-interactive functions.  I don't think that you can expect—and, for that matter, that we can guarantee—that the buffer list doesn't change during the normal course of Flycheck's syntax checks.  What do you use `buffer-list-update-hook` for?  Why is it crucial for you that the buffer list does not change during a syntax check?

**Comment by cpitclaudel** [comment] 2016-09-09 15:41
```
buffer-list-update-hook is a variable defined in ‘C source code’.
…
Documentation:
Hook run when the buffer list changes.
Functions running this hook are, ‘get-buffer-create’,
‘make-indirect-buffer’, ‘rename-buffer’, ‘kill-buffer’,
‘bury-buffer-internal’ and ‘select-window’.
```

IOW, this hook runs all the time :)

> The checker go-vet seems temporary switch current buffer … but trigger the `buffer-list-update-hook`, which may confuse other code. 

Only badly-written-code, which should be fixed ^^ Which code do you have in mind?

**Comment by hex2010** [comment] 2016-09-09 15:58
I use `buffer-list-update-hook` to flash the window when `current-buffer` or `selected-window` change,  in this case i got the window flash frequently when editing golang source.  

I know few about lisp, and failed to find another way to get the trick work.  for the same reason I hard to setup a clean emacs environment to track down the issue.  

This issue is not critical for me,  when disable `go-vet` it just work well as desired. no unwanted flash, no notable lag, really awesome.

I still can not reproduce the flash in a clean emacs,  and pure flycheck seems not work alone.  I remove my .emacs and .emacs.d to create a new clean emac environment. then: 

 1. install `flycheck` and `go-mode` from `melpa` 
 1. write .emacs file like below, save, exit emacs.
 1. run emacs from terminal so it can find the go tools in $PATH: `emacs ~/gopath/src/hx/tinymail/tinymail.go`
 1. `M-x flycheck-mode RET`,  edit the tinymail.go file a bit, then check the `*Messages*` buffer.

Here is the new clean .emacs file:
 ```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(setq package-enable-at-startup nil)
(package-initialize)

(require 'flycheck)
(add-hook 'buffer-list-update-hook (function (lambda ()
					       (message (prin1-to-string (current-buffer))))))

custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (go-mode flycheck))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```
![flycheck-issue](https://cloud.githubusercontent.com/assets/13978929/18393603/94af46bc-76a5-11e6-90b7-8d54e8b04974.png)

sorry for my poor emacs knowledge and poor English.

**Comment by hex2010** [comment] 2016-09-09 16:01
This is my try, indeed.
```
(defvar hx-buffer-or-window-change-hook nil)

(defvar hx-current-buffer-and-window nil)

(defun hx-current-buffer-and-window ()
  "Get current buffer and selected window."
  (cons (current-buffer) (frame-selected-window)))
(defun hx-ingore-buffer (buffer)
  "Return whether to ignore BUFFER"
  (or (null buffer)
      (string-prefix-p " " (buffer-name buffer))))

(defun run-hx-buffer-or-window-change-hook ()
  "Run hx-buffer-or-window-change-hook on certain condition."
  (if (not (hx-ingore-buffer (current-buffer)))
	  (progn (if (not (equal hx-current-buffer-and-window (hx-current-buffer-and-window)))
				 (progn
;;				   (message (prin1-to-string (hx-current-buffer-and-window)))
						(run-hooks 'hx-buffer-or-window-change-hook)))
			 (setq hx-current-buffer-and-window (hx-current-buffer-and-window)))))

(add-hook 'buffer-list-update-hook 'run-hx-buffer-or-window-change-hook)

(require 'nav-flash)
(add-hook 'hx-buffer-or-window-change-hook 'nav-flash-show)

```

**Comment by lunaryorn** [comment] 2016-09-10 17:12
What about `window-configuration-change-hook`?  I think the hook should cover your use case.

If it doesn't work either you can also write a global minor mode that hooks into `post-command-hook`, remembers the current buffer and the current window in variables and flashes if the remembered values don't match the current ones. 

In any case I'm closing this issue because we don't think that this is actually an issue in Flycheck.

**Closed by lunaryorn** 2016-09-10 17:12 UTC
Labels: language support
