### ISSUE TITLE
Exclude buffers from being checked when Flycheck is globally enabled.

### ISSUE THREAD

**Issue by zeroDivisible** [flycheck/flycheck#885] opened 2016-02-26 10:39 UTC
Hey

Just wanted to ask - I'm spending some time recently trying to hunt all the things which might be causing "slowness" of my Emacs. With few dozens packages installed, I got to the stage when i.e. moving to a next line had a really slight, unnecessary delay associated. 

Few things to know: 
* I have `flycheck` enabled globally
* I have few big packages running (i.e. Evil, Flycheck, Helm, `company-mode` among others - I guess it's a typical setup, maybe Evil being unusual)

While testing for changes, I roughly:
* opened a random file
* ran profiler with `profiler-start`
* ran `helm-M-x`, typed `profiler-` and was pressing down arrow to select `profiler-report`. 

That's how the report ended looking like
```
- command-execute                                                 801  89%
 - call-interactively                                             801  89%
  - byte-code                                                     801  89%
   - helm-M-x-read-extended-command                               801  89%
    - helm-comp-read                                              800  88%
     - helm                                                       800  88%
      - apply                                                     800  88%
       - helm                                                     800  88%
        - apply                                                   800  88%
         - helm-internal                                          800  88%
          - helm-read-pattern-maybe                               791  87%
           - read-from-minibuffer                                 689  76%
            - timer-event-handler                                 569  63%
             - apply                                              566  62%
              - helm-process-delayed-sources                      433  48%
               - helm--compute-sources                            420  46%
                - helm-render-source                              306  34%
                 - helm-insert-match                              291  32%
                  - insert                                        291  32%
                   - flycheck-handle-change                       291  32%
                    - flycheck-buffer-automatically                291  32%
                     - flycheck-may-check-automatically                291  32%
                      + file-exists-p                               9   1%
                 + helm-insert-header-from-source                  15   1%
                - helm--collect-matches                           114  12%
                 - helm-compute-matches                           114  12%
                  - helm-process-filtered-candidate-transformer                 78   8%
                   + helm-composed-funcall-with-source                 78   8%
                  + helm-get-cached-candidates                     30   3%
                  + helm-match-from-candidates                      5   0%
                 helm-display-mode-line                             8   0%
               + helm-update-move-first-line                        5   0%
              + #<compiled 0x44f606f5>                            132  14%
             + timer-activate                                       3   0%
            + command-execute                                      12   1%
            + minibuffer-inactive-mode                             10   1%
            + redisplay_internal (C function)                       5   0%
            + #<lambda 0x427aff1f>                                  1   0%
            + flycheck-perform-deferred-syntax-check                  1   0%
           + helm-update                                            4   0%
          + helm-initialize                                         8   0%
          + #<compiled 0x41bf706b>                                  1   0%
+ ...                                                              95  10%
- timer-event-handler                                               2   0%
 - apply                                                            2   0%
  + sp-show--pair-function                                          2   0%
+ flyspell-post-command-hook                                        1   0%
```

This relatively simple operation ended calling `flycheck-handle-change` around 300 times. I guess that's not that bad, but I think it might be unnecessary in Helm buffers as in the end I don't want anything to be checked there. 

So my question is: assuming that I did everything correctly, what would be the advised way of having Flycheck enabled globally - but excluding all helm buffers from being checked?

Thanks!

**Comment by lunaryorn** [comment] 2016-02-26 10:45
Flycheck should not enable itself in Helm buffers anymore since recently, see #883.  Can you please make sure that you have recent versions of Flycheck and Helm installed?

**Comment by zeroDivisible** [comment] 2016-02-26 10:54
@lunaryorn brilliant, thanks for the tip! I removed my `~/.emacs.d/elpa` and redownloaded everything, it looks like Flycheck really does not enable itself in helm buffers now:

```
- command-execute                                                 568  79%
 - call-interactively                                             568  79%
  - byte-code                                                     566  79%
   - helm-M-x-read-extended-command                               566  79%
    - helm-comp-read                                              565  79%
     - helm                                                       564  79%
      - apply                                                     564  79%
       - helm                                                     564  79%
        - apply                                                   564  79%
         - helm-internal                                          564  79%
          - helm-read-pattern-maybe                               549  77%
           - read-from-minibuffer                                 406  57%
            - timer-event-handler                                 249  35%
             - apply                                              247  34%
              - helm-process-delayed-sources                      140  19%
               - helm--compute-sources                            122  17%
                - helm--collect-matches                           121  17%
                 - helm-compute-matches                           121  17%
                  + helm-process-filtered-candidate-transformer                 95  13%
                  + helm-get-cached-candidates                     18   2%
                  + helm-match-from-candidates                      7   0%
                  + helm--fuzzy-match-maybe-set-pattern                  1   0%
                + helm-render-source                                1   0%
               + helm-update-move-first-line                       11   1%
                 helm-display-mode-line                             7   0%
              + #<compiled 0x46aeb96f>                            101  14%
              + auto-revert-buffers                                 4   0%
             + timer-activate                                       1   0%
            + command-execute                                      19   2%
            + minibuffer-inactive-mode                              9   1%
            + redisplay_internal (C function)                       3   0%
           + helm-update                                           22   3%
          + helm-initialize                                        14   1%
          + #<compiled 0x454f05f5>                                  1   0%
     + helm-make-source                                             1   0%
  + funcall-interactively                                           2   0%
- ...                                                             117  16%
   Automatic GC                                                   116  16%
 - helm-default-display-buffer                                      1   0%
  - display-buffer                                                  1   0%
   + apply                                                          1   0%
+ timer-event-handler                                              13   1%
+ delete-selection-pre-hook                                         6   0%
+ flyspell-post-command-hook                                        4   0%
+ redisplay_internal (C function)                                   2   0%
+ evil-repeat-pre-hook                                              1   0%
```

(that's roughly the same test, numbers don't match, but you get the idea).

Thanks for the quick resolution! :)

**Comment by lunaryorn** [comment] 2016-02-26 10:56
@zeroDivisible Great, it feels good to see that the work of #883 already pays off :blush: Thank you very much for your report and for your quick feedback on our changes, particularly for the detailed profile information.  That's awesome! :+1: :clap:

**Comment by lunaryorn** [comment] 2016-02-26 10:56
I am closing this issue as duplicate of #883.

**Closed by lunaryorn** 2016-02-26 10:56 UTC
Labels: B-waiting for feedback
