### ISSUE TITLE
(flycheck-verify-setup) Wrong type argument: listp, "32-cvs"

### ISSUE THREAD

**Issue by CdeMills** [flycheck/flycheck#1353] opened 2017-10-27 21:23 UTC
Hello,
I installed the flycheck package from MELPA. To verify it, I first did "M-X flycheck-verify-setup" which fails with the strange reported error.

Platform: CentOS 7 X86_64, Emacs 24.3.

I have a fairly complex .emacs with lots of functions accumulated over the years. Starting with an .emacs containing only
(add-hook 'after-init-hook #'global-flycheck-mode)
This error doesn't appear.

Any idea which kind of function could interact and generate such error ? My full .emacs is included

Regards
Pascal
[my-emacs.txt](https://github.com/flycheck/flycheck/files/1423500/my-emacs.txt)

**Comment by CdeMills** [comment] 2017-10-27 21:44
OK. Found the culprit: package el-get; see https://github.com/dimitri/el-get

Any idea of what's wrong with it ?

Regards

Pascal

**Comment by cpitclaudel** [comment] 2017-10-27 22:27
Can you show a backtrace ? Use M-x toggle-debug-on-error before reproducing the error.

**Comment by CdeMills** [comment] 2017-10-28 09:09
Pure sillyness. Error depends on the time when debug-on-error is toggled.

Scenario 1:
emacs -q
M-x toggle-debug-on-error
load .emacs; byte-compile and evaluate it
load sometext
M-x flycheck-mode
M-x flycheck-verify-setup: no error

Scenario 2
emacs (load .emacs which loads el-get and add a hook to flycheck)
load sometext
M-x flycheck-mode
M-x flycheck-verify-setup: error

Scenario 3
emacs -q
load .emacs; byte-compile and evaluate it
load sometext
M-x toggle-debug-on-error 
M-x flycheck-mode
M-x flycheck-verify-setup: got a BT
Debugger entered--Lisp error: (wrong-type-argument listp "32-cvs")
  version-list-=("32-cvs" (20171026 610))
  pkg-info-version-info(flycheck)
  flycheck-version()
  flycheck--verify-print-footer(#<buffer AutoRefFR.tex>)
  flycheck-verify-setup()
  call-interactively(flycheck-verify-setup record nil)
  command-execute(flycheck-verify-setup record)
  execute-extended-command(nil "flycheck-verify-setup")
  call-interactively(execute-extended-command nil nil)

Summary: no issue with early debug-on-error-toggle; issues if toggle after the flycheck-hook is activated.

Regards

Pascal



Regards

Pascal

**Comment by cpitclaudel** [comment] 2017-10-29 15:29
OK, thanks :) Can you try running (`M-:`) the following: `(pkg-info-library-version 'flycheck)`? On my machine it returns `(32 -4)`.  Does it return `"32-cvs"` on yours?

A simpler way to reproduce the bug should be to run `(pkg-info-version-info 'flycheck)`, btw; can you confirm that this does reproduce it?

Thanks!

**Comment by cpitclaudel** [comment] 2018-08-13 20:32
Thanks.  This new backtrace is surprising.  Can you also show the backtrace printed by `(pkg-info-version-info 'flycheck)` (I imagine it will be similar…)

I'd like to reproduce the issue locally, but I have no experience with el-get; how did you install Flycheck?

**Comment by Profpatsch** [comment] 2018-08-14 11:55
> Can you also show the backtrace printed by (pkg-info-version-info 'flycheck)

```
Debugger entered--Lisp error: (wrong-type-argument stringp package-desc)
  signal(wrong-type-argument (stringp package-desc))
  epl-package-from-lisp-file("/home/philip/.emacs.d/elpa/flycheck-20180614.1235/flycheck.el")
  epl-package-from-file("/home/philip/.emacs.d/elpa/flycheck-20180614.1235/flycheck.el")
  pkg-info-library-version(flycheck)
  pkg-info-version-info(flycheck)
  eval((pkg-info-version-info 'flycheck) nil)
  eval-expression((pkg-info-version-info 'flycheck) nil nil 127)
  funcall-interactively(eval-expression (pkg-info-version-info 'flycheck) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

> how did you install Flycheck?

I use the version provided by Spacemacs; I think they just add the melpa repository and call the correct `package.el` versions to update all packages to their newest versions when updating.

**Comment by CdeMills** [comment] 2018-08-18 08:04
Short follow-up: I disabled el-get and switched to the official Emacs packaging system (ELPA, MELPA, ...); that solved this particular problem.

Regards

Pascal

**Comment by fmdkdd** [comment] 2018-08-20 09:51
@Profpatsch 

> Debugger entered--Lisp error: (wrong-type-argument stringp package-desc)

Try to trash your `epl.elc` and byte-compile it again.  See [this comment](https://github.com/flycheck/flycheck/issues/1484#issuecomment-406209373).

**Comment by Profpatsch** [comment] 2018-08-21 17:53
Thanks, that solved it!

**Comment by fmdkdd** [comment] 2018-08-22 08:30
Closing since both users have solved their issue.  Feel free to reopen if the issue reappears.

**Closed by fmdkdd** 2018-08-22 08:30 UTC
