### ISSUE TITLE
Zero-based columns in javascript-eslint checker

### ISSUE THREAD

**Issue by hekto** [flycheck/flycheck#639] opened 2015-05-06 10:30 UTC
Flycheck version: 0.24alpha (package: 20150503.1047)
eslint version v0.20.0

I believe there is a `(flycheck-increment-error-columns errors)` missing in the error-filter of the javascript-eslint checker.

This change works for me:
```diff
- (flycheck-sanitize-errors errors))
+ (flycheck-sanitize-errors (flycheck-increment-error-columns errors)))
```

Do you want me to make a pull request with that change?

**Comment by hekto** [comment] 2015-05-06 12:15
Reading #578 got me thinking... Could it be that the checkstyle format is supposed to be zero-based when it comes to columns? 

I haven't found any spec for the xml format, but at least internally it looks like checkstyle is storing lines one-based and columns zero-based.

If that is the case, the proper solution would be to increment the column inside `flycheck-parse-checkstyle` instead.

**Comment by hekto** [comment] 2015-05-06 12:33
So.. change this in `flycheck-parse-checkstyle`:

```diff
(flycheck-string-to-number-safe .line)
- (flycheck-string-to-number-safe .column)
+ (+ 1 (flycheck-string-to-number-safe .column))
(pcase .severity
```

**Comment by lunaryorn** [comment] 2015-05-06 12:41
I wouldn't bet on every tool using Checkstyle XML in a consistent way.  I doubt that most tools give any thought about column numbering.  Most probably just dump their internal representation into Checkstyle XML, with whatever column offset they happen to use internally—or worse, with whatever column offset the underlying parser library happens to use.

Did you check whether all other checkers that use checkstyle in Flycheck increment columns in their error filters?  I doubt that they all do, so changing `flycheck-parse-checkstyle` is not an option.

I'd welcome a pull request, though, that fixes ESLint, but please update the test cases accordingly.  You can run them locally with `test/run.el '(checker javascript-eslint)'`

**Comment by lunaryorn** [comment] 2015-05-06 14:17
Closing as duplicate of #640

**Closed by lunaryorn** 2015-05-06 14:17 UTC
