### ISSUE TITLE
File hangs flycheck-mode

### ISSUE THREAD

**Issue by zot** [flycheck/flycheck#855] opened 2016-01-13 12:43 UTC
This file hangs emacs when I turn on flycheck-mode.  ctrl-g will not interrupt it, I have to kill the process to stop it.

https://gist.github.com/zot/a1b0842f1e81ccda7323

**Comment by zot** [comment] 2016-01-13 12:59
I tried lunaryorn's workaround here: http://emacs.stackexchange.com/a/2541/10669 and it does prevent flycheck from turning on when I load the file but it does not prevent flycheck from turning on when restoring the emacs desktop.

**Comment by lunaryorn** [comment] 2016-01-13 13:25
@zot Please do add more information to your report:

- What operating system are you on? Are you probably affected by #794, which is being fixed in #850?
- What syntax checker do you use?  Please show the output of `flycheck-verify-setup`.
- What is your Flycheck version?  Look at `M-x flycheck-version`.

**Comment by lunaryorn** [comment] 2016-01-13 13:25
Please also try to improve your issue description: What do you mean with "hang"?  Does Emacs freeze? Or does Flycheck just not finish its syntax check?

**Comment by zot** [comment] 2016-01-13 14:07
I'm on windows.  I saw great hostility towards windows and the users of windows from you on issue #794 and, much as I'd like to, I can't use Linux at this time.

Should I bother elaborating on this problem or is this a collective FU from the flycheck team?

**Comment by zot** [comment] 2016-01-13 14:30
Emacs completely freezes on turning on flycheck-mode in even a small coffeescript file and I just tested this on a vanilla Emacs config with only these packages loaded and a [small (200 line) coffee script file](https://gist.github.com/zot/b5e6d03e6e51543e873b).

One thing that might be relevant is that the files that are hanging are AMD files where all of the code is inside of a call to define().

- js-doc
- js2-refactor
- coffee-mode
- js2-mode
- literate-coffee-mode
- flycheck
- flymake-coffee
- flymake-jshint
- flymake-jslint
- flymake-json
- flymake-yaml

flycheck-verify-setup reports:
```
Syntax checkers for buffer base.coffee in coffee-mode:

  coffee
    - predicate:  t
    - executable: Found at c:/Users/bill/AppData/Roaming/npm/coffee.cmd

  coffee-coffeelint
    - predicate:  t
    - executable: Found at c:/Users/bill/AppData/Roaming/npm/coffeelint.cmd

Flycheck Mode is enabled.
```
flycheck-version reports: 0.26snapshot (package: 20160111.1516)

**Comment by lunaryorn** [comment] 2016-01-13 14:34
This is very likely the same as in #794.  I am closing this issue as a duplicate.  We are already in the process of fixing it in #850, but there are a some minor questions that still need answers first.  Please be patient.  Should your issue persist after #850 is merged and #794 fixed, we can re-open this issue again.

By the way, you do not need these `flymake` packages for Flycheck.  You may safely remove them.

----

Please understand that Flycheck does not support Windows officially.  We make this very explicit in our  [our manual](http://www.flycheck.org/manual/latest/Installation.html#index-Windows) and in our [Github Readme](https://github.com/flycheck/flycheck#installation).  

Following the discussion in #794 I have changed and clarified our policy on [Windows-only](http://www.flycheck.org/getting-help.html#windows-only-issues) issues: We will not close these anymore, but we will still not make any attempt to fix them, and leave them to the community, under a special label.  

I am sorry; I understand that the situation is not satisfying for Windows users, but this policy will not change until Flycheck is joined by a developer who dedicates themselves to maintaining Windows support, and takes care of all Windows issues.  Until then, there's no base for discussing our Windows policy.

----

If you think that my behaviour in #794 was not appropriate, please contact @cpitclaudel or me to explain your specific complaints.  Thank you

**Closed by lunaryorn** 2016-01-13 14:34 UTC
Labels: B-waiting for feedback, S-blocked

**Comment by zot** [comment] 2016-01-13 14:42
I understand that you can't fix windows-specific issues if there are no developers on the team who use windows and I think this is a reasonable position.  What bothered me was marking the issue as invalid *before* attempting to reproduce it on Linux/UNIX -- that came off like a slap in the face to me.

Believe my, I'd much rather be using Linux right now but like a lot of other people, I suspect, I have to use windows for work at this point.  It sucks and I hate it.  I hate the crappy file locking and a lot of other things.  Given that, things that *appear* to bash windows **users** just make the whole experience worse for me :).

Sorry I slapped back -- I commented in anger.

**Comment by zot** [comment] 2016-01-13 14:45
If it helps, I can send my .emacs.d directory to test with.

**Comment by cpitclaudel** [comment] 2016-01-13 15:13
Hi Bill,

Thanks for reporting this bug; as you may have seen from #794, I've been looking at a similar bug on Windows, and as you may have seen from #850, we're working on a fix, along with Emacs devs to figure out why this bug exists in the first place. However, neither Sebastian nor me use Windows as our primary system, so detecting and fixing these issues is not something we can commit to. Please don't take this as hostility; we simply lack the time and resources. 

(On a more personal note, I don't dislike windows as an OS; some of my Emacs packages that depend on Flycheck were written at least in part to provide Emacs support for languages only supported by Visual Studio, so I have a personal interest for Flycheck to work there; but that personal interest is disjoint from my responsibilities as a maintainer).

What would be extremely useful for us is for you to test the fix that is under development, as described in #794 (see #850). If you want to help even more, you could try to compile Emacs from source, and test the patch that was recently committed to the emacs-25 branch; this would be very convenient, as my experience compiling complex projects on Windows is limited.

Your .emacs.d wouldn't be very useful in trying to understand this bug; in general, bug reports are most useful when they don't depend on a user's personal configuration. A recipe to reproduce this bug would be much more useful if it started by "run emacs -Q".

Thanks for your help in making Flycheck work well for everyone!

**Comment by lunaryorn** [comment] 2016-01-13 15:31
@cpitclaudel Thank you for joining our discussion.  You've said things much better than I did.  Thank you very much.

@zot Adding to what @cpitclaudel has said, I'd like to thank you for your help, your patience and for your understanding.

I'd also like to clarify that we always try to reproduce all issues, at least superficially, regardless of whom reported them and what OS the reporter used, and I did so in case of #794 as well, closing it only after I was unable to reproduce the bug on OS X and on Linux, with different eslint, nodesjs and Emacs versions.  

However after #794 I now understand that closing an issue conveys an entirely different message to users.  As a result, we'll not close Windows issues anymore, but instead maintain [a list of open Windows issues](https://github.com/flycheck/flycheck/labels/B-Windows%20only) to make all Windows users aware of potential problems and help them to discover where they can help us to achieve better Windows support.

It was not my intention to demean or marginalise, let alone offend, Windows users.  I should have taken more time to explain why I closed the issue, and I'd like to apologise for my misleading comment, and for the offense that you have taken.  Sorry.

Thank you for helping to make Flycheck better, and in particular for helping me to improve my communication with our users.

**Comment by zot** [comment] 2016-01-13 16:17
Thanks, guys.

Chunking output to 4096 looks like it does the trick for me.  My only trouble was properly integrating the patch into my init.  I recently started to use spacemacs and I like the layer framework it provides but putting the patch into dotspacemacs/user-init didn't work because flycheck was not yet available for require and putting it into dotspacemacs/user-config didn't work because it was to far in the init process, the desktop had already been loaded and emacs was already hung.

Hopefully this will help other spacemacs users who are also having this problem.  The fix for me was to make a dotspacemacs/patch-flycheck function and use function advice in dotspacemacs/user-init.  It's kind of a lame solution but it works.  I'll be sending the spacemacs team a note on this -- maybe they can make another scaffolding function for this purpose.  Here's my dotspacemacs/user-init:

```
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put almost any
user code here.  The exception is org related code, which should be placed in
`dotspacemacs/user-config'."
  (advice-add 'configuration-layer//load-packages :after
              (lambda (&rest args)
                (dotspacemacs/patch-flycheck))))
```

**Comment by lunaryorn** [comment] 2016-01-13 16:22
@zot We'll properly integrate the fix in Flycheck soon.
