### ISSUE TITLE
"Suspicious state" when editing unterminated docstrings in Python

### ISSUE THREAD

**Issue by fice-t** [flycheck/flycheck#948] opened 2016-04-20 04:46 UTC
When you're editing a docstring without closing triple quotes in Python that's not immediately followed by EOF, then the following message pops up:
```
Suspicious state from syntax checker python-pycompile: Checker python-pycompile returned non-zero exit code 1, but no errors from output:   File "/tmp/flycheck1595szW/test.py", line 4
    """ Here we have an unterminated docstring.
    x + y
                                               
        ^
SyntaxError: EOF while scanning triple-quoted string literal


Checker definition probably flawed.
```

To reproduce: Just try and remove the ending triple quotes from the following:
```python
def test(x, y):
    """ Here we have an unterminated docstring."""
    x + y
```

This was produced in `emacs -Q` with `Flycheck version: 26snapshot (package: 20160419.712)` on `GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.18.9)`

**Comment by lunaryorn** [comment] 2016-04-20 09:01
@fice-t Would you mind to tell me your Python version?

**Comment by lunaryorn** [comment] 2016-04-20 09:03
Never mind, I can reproduce it.  It appears that the `python-pycompile` pattern doesn't handle multiline messages well.  

I'll fix this issue at some point, however, `python-pycompile` is intended as a very last resort.  `python-flake8` and `python-pylint` are generally preferred and should be used instead.  Hence this issue has rather low priority for me personally.

Pull requests would be very welcome.  @fice-t Would you give it a try?

**Comment by fice-t** [comment] 2016-04-20 18:19
Ah, I still use the default checkers. I'll have to get around to customizing them.

Anyway, I changed the 
```elisp
(= 2 (zero-or-more not-newline) "\n")
```
in the checker definition to
```elisp
(>= 2 (zero-or-more not-newline) "\n")
```
and it fixes the issue. Is there a reason why `= 2` was chosen?

**Comment by lunaryorn** [comment] 2016-04-20 20:30
@fice-t I don't know.  It's been like that since it was merged, see https://github.com/flycheck/flycheck/pull/484.  I guess it's safe to change, isn't it?

Would you mind to try the modified pattern with different syntax errors and different files?

**Comment by fice-t** [comment] 2016-04-20 21:35
Seems to work the same as before in other cases/files.

**Closed** 2016-04-28 22:02 UTC
Labels: A-language support, E-beginner friendly, K-bug, P-low, S-in progress
