### ISSUE TITLE
No checker for Jade 

### ISSUE THREAD

**Issue by robbyoconnor** [flycheck/flycheck#680] opened 2015-07-07 03:29 UTC
There does not seem to be any support for [jade](http://jade-lang.com), and I am curious why this is the case. Should I write it, or is there a rationale behind why it does not exist and not spend the energy of writing it only to have the PR rejected. I just wanted to open a dialogue.

**Comment by robbyoconnor** [comment] 2015-07-07 03:40
Going to do a PR (pending)

**Comment by lunaryorn** [comment] 2015-07-07 07:32
@robbyoconnor There's no rationale other than that none has yet bothered to write a syntax checker for it. I don't even know what Jade is.

**Comment by robbyoconnor** [comment] 2015-07-07 11:11
[Jade](http://jade-lang.org) -- it's a templating language used in node.js web apps

**Comment by lunaryorn** [comment] 2015-07-14 07:56
Oh, please excuse that I did not answer your edit to tie last comment.  GitHub does not send notifications for edits hence I simply missed it.  Please do not use edits to add information to your comments.  Instead, just write a new comment.

Generally I reserve the right to refuse and close pull requests and issues at my own discretion.  You open PRs at your own risk. I will look at #686 but I don't promise anything.  Still your effort is never lost, you can always copy the code to your personal Emacs configuration or fork Flycheck.

Closing as duplicate of #686.  Please let us continue the discussion over there.

**Comment by lunaryorn** [comment] 2015-07-14 08:00
Ok let's continue this discussion here, the other issue that you opened is really redundant.

**Comment by lunaryorn** [comment] 2015-07-14 08:04
Adding to my previous comment:  I will not close a pull request only because I don't know a language.  That's never been a criterion for me and I only know probably half of the languages that Flycheck supports.

**Comment by robbyoconnor** [comment] 2015-07-14 09:32
This arose out of a need I had -- I wanted to implement it -- it seemed (to me at least) that you had no interest in implementing this (and that's not a problem) -- I wanted it, I made it happen...yay FOSS :smile:  -- What was the issue with my PR?

**Comment by robbyoconnor** [comment] 2015-07-14 09:47
Should I extract this into a separate package -- This is something I believe others would benefit from and I'd **LOVE** it to be part of the core of flycheck, but am just confused...I mean **ZERO** disrespect

**Comment by lunaryorn** [comment] 2015-07-14 12:04
Please consider all that I said above irrelevant.  I didn't realize that #686 was a pull request.  I'm really really sorry.

Closing this one, I'll review #686 and merge ASAP.  Looks really good, many thanks for your contribution!

**Closed by lunaryorn** 2015-07-14 12:04 UTC
Labels: checker
