### ISSUE TITLE
Flycheck for C++

### ISSUE THREAD

**Issue by JackalopeGit** [flycheck/flycheck#1511] opened 2018-10-16 06:41 UTC
I have a file "framework.cpp"
with single line`#include "framework.h"`
`C-c ! l` shows next:

```
     1     warning         In include ./framework.h (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
```
Switching to file `framework.h`
```
1   9 warning         #pragma once in main file (c/c++-clang)
     3     error           In include ./render/renderer.h (c/c++-clang)
     3     error           In file included from (c/c++-clang)
```
Switching to file `render/renderer.h`
```
1   9 warning         #pragma once in main file (c/c++-clang)
     3     warning         In include ./device/device.h (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     warning         In include ./draw_stages/draw_stages.h (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     4     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
     5     error           In file included from (c/c++-clang)
```
And etc.. etc... etc..
And finally in the some file
```
1   9 warning         #pragma once in main file (c/c++-clang)
     4  10 error           'cstring' file not found (c/c++-clang)
```
```
#pragma once

#include <vulkan/vulkan.h>
#include <cstring>

//more code
```
What I expected: no 100 deep file routines, no useless spam like one hundred "in file included from" without "PATH/FILE_THAT_INCLUDED", and finally `#include <cstring>` mustn't be an error.

`M-x flycheck-verify-setup`
```
Syntax checkers for buffer misc.h in c-mode:

  c/c++-clang
    - may enable: yes
    - executable: Found at /usr/lib/llvm/7/bin/clang

  c/c++-gcc
    - may enable: yes
    - executable: Found at /usr/bin/gcc

  c/c++-cppcheck
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31
Emacs version:    26.1
System:           x86_64-pc-linux-gnu
Window system:    x
```
System `gentoo`

Also this config didn't work when I call `flycheck-compile c/c++-clang`, please tell me why.
```
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((c++mode .
	  (
	      (flycheck-clang-language-standard . c++17)
	      (flycheck-clacn-no-exceptions . t)
	      (flycheck-clang-no-rtti . t)
	      (flycheck-clang-warnings .  "everything no-pragma-once-outside-header no-missing-braces no-c++98-compat-pedantic no-nested-anon-types no-zero-length-array no-c++98-c++11-compat-binary-literal no-comma no-c++98-compat no-gnu-anonymous-struct no-c99-extensions no-vla-extension no-c++17-extensions no-switch-enum no-vla")
	      (flycheck-clang-args . nil)
	      )
))
```

**Comment by fmdkdd** [comment] 2018-10-16 13:17
> C-c ! l shows next:
     1     warning         In include ./framework.h (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)
     1     error           In file included from (c/c++-clang)

Yikes.  That's quite useless indeed.  Do you have a C++ repo where I can try to reproduce and see how we can extract more information for these errors?

At the very least, we could dedupe errors.

>  finally #include <cstring> mustn't be an error.

I think what's happening here is that `flycheck-clang` thinks you are using C, based on the major mode you are using.  `.h` files are associated to C by default, not C++.  You could override that with a .dir-locals.

>  this config didn't work when I call flycheck-compile c/c++-clang, please tell me why.

Many reasons.  You have a typo in `flycheck-clacn-no-exceptions`, and the value of `flycheck-clang-language-standard` should be a string, i.e., "c++17".  Also, the `-warnings` variable should be a list of strings:
`flycheck-clang-warnings . ("everything" "no-pragma-once-outside-header" ...)`.  I suggest you look up the documentation for these variables to determine what values are expected.

Lastly, you should take a look a flycheck extensions like [flycheck-irony](https://github.com/Sarcasm/flycheck-irony) which may be more suited towards checking whole projects.

**Comment by JackalopeGit** [comment] 2018-10-16 14:58
I am changed my local `.dir-local.el` file, but it still unset.
```
((c++mode .((flycheck-clang-include-path . ("/usr/include/libxml2"))
	    (flycheck-clang-language-standard . "c++17")
	    (flycheck-clang-no-exceptions . t)
	    (flycheck-clang-no-rtti . t)
	    (flycheck-clang-warnings . ("no-pragma-once-outside-header" "everything" "no-pragma-once-outside-header" "no-missing-braces" "no-c++98-compat-pedantic" "no-nested-anon-types" "no-zero-length-array" "no-c++98-c++11-compat-binary-literal" "no-comma" "no-c++98-compat" "no-gnu-anonymous-struct" "no-c99-extensions" "no-vla-extension" "no-c++17-extensions" "no-switch-enum no-vla"))
	    (flycheck-clang-args . nil))
))

((nil . ((eval . (c++-mode)))))

```
And I confirm, that `.h` associated to `C`.
`C-h v` for variables shows, that they are not set correctly.

I am correctly understand, that flycheck can't show output about different files?
The only way to see them is a `flycheck-compile`?

**Comment by fmdkdd** [comment] 2018-10-16 15:21
> ((c++mode

should be `c++-mode`.

> I am correctly understand, that flycheck can't show output about different files?

Not sure what you mean.  You want errors for different files to appear in `C-c ! l`?

**Comment by JackalopeGit** [comment] 2018-10-17 02:06
> > ((c++mode
> 
> should be `c++-mode`.
> 
Okay, thanks, variables works now. But how to set `c++-mode` by default in `.dir-locals.el`? Maybe better to install project manager to emacs?
> > I am correctly understand, that flycheck can't show output about different files?
> 
> Not sure what you mean. You want errors for different files to appear in `C-c ! l`?
When I am working with templates, template instantiation can cause errors from template files, that don't shown in template file, because only instantiation usage can provide errors, for example.

Okay, i describe this. I have vector library, that defines template vector with overloaded operator +=, looks like this
```

template<unsigned int size, typename type>
struct vector : public vector_base<size, type>
{
    template<typename other_t> constexpr inline
    vector& operator += (const vector<size, other_t>& other);

    type _[size];
}
template<unsigned int size, typename type> template<typename other_t> constexpr inline 
vector<size, type>& vector<size, type>::operator += (const vector<size, other_t>& other)
{
     for (unsigned int i = 0; i < size; ++i)
         _[i] += other[i];
     return *this;
}
```
And duo this, `type` member must have += operator.
Now, I instantiate in some other file this template:
```
struct dummy {};
math::vector<3, dummy> vec1, vec2;
vec1 += vec2;
```
struct dummy doesn't have overloaded operator +=, so
`C-c ! l` shows me 
```
In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h

In include ./system.h
```
In this error QtCreator, as an example of imitation, shows this information

```
base.hpp:68:18: error: no viable overloaded '+='
--
system.cpp:1:10: note: in file included from /home/larry/game/game/system/system.cpp:1:
system.h:3:10: note: in file included from /home/larry/game/game/system/system.h:3:
renderer.h:4:10: note: in file included from /home/larry/game/game/system/../render/renderer.h:4:
draw_stages.h:12:10: note: in file included from /home/larry/game/game/system/../render/draw_data/../draw_stages/draw_stages.h:12:
offscreen.h:8:10: note: in file included from /home/larry/game/game/system/../render/draw_stages/offscreen/offscreen.h:8:
descriptors.h:3:10: note: in file included from /home/larry/game/game/system/../render/draw_stages/offscreen/descriptors.h:3:
math.h:6:10: note: in file included from /home/larry/game/game/system/../math/math.h:6:
...
noise_test.hpp:215:53: note: in instantiation of function template specialization 'seeds::generate_texture_icosagedron_quad<seeds::noise_test_type::GREEN_PLANET>' requested here
system.cpp:163:17: note: in instantiation of function template specialization 'seeds::noise_test_init<seeds::noise_test_type::GREEN_PLANET>' requested here
system.cpp:11:26: note: in instantiation of function template specialization 'System::Object::init<seeds::noise_test_type::GREEN_PLANET>' requested here

```
I can see full trace and click to any line for "go to statement".

**Comment by fmdkdd** [comment] 2018-10-17 13:41
>  But how to set c++-mode by default in .dir-locals.el?

See https://stackoverflow.com/q/3312114 for various ways to do it.

> Okay, i describe this (...)

Yep, there are at least two issues here with Flycheck regarding C++.  The first one is that we are eating valuable information from the error message, which gives us the lame "In include ./system.h".  I believe shortening the error message was done on purpose (see #451), but the fact that we are only seeing "./system.h" in your case is probably  a genuine bug.  I can't reproduce without a working example.  Can you build a minimal reproduction of code that triggers this issue?  Or point me to a public repository that has this issue.  I don't use C++ that much, so I can't just write the code that would trigger it.

The second issue is that  Flycheck treats the "note: in instantiation..." as a separate error from the "error: no viable overloaded '+='", whereas in the original clang output they are related.  There's not much we can do without enhancing the parsing of errors, as right now they are output as different lines, so there's no way to know for sure they should be grouped.  But this is, all in all, a minor annoyance.

**Comment by JackalopeGit** [comment] 2018-10-19 10:18
> Can you build a minimal reproduction of code that triggers this issue? Or point me to a public repository that has this issue. I don't use C++ that much, so I can't just write the code that would trigger it.

https://github.com/JackalopeGit/b4343j423

**Comment by fmdkdd** [comment] 2018-10-24 16:36
> https://github.com/JackalopeGit/b4343j423

Thanks, that's really helpful.  So here's what I'm seeing when running `clang main.cpp`:

```

In file included from main.cpp:1:
In file included from ./template.h:3:
In file included from ./vector.h:4:
./vector_imp.hpp:8:28: error: type 'const vector<3, Dummy>' does not provide a subscript operator
        member_array[i] += other[i];
                           ^~~~~ ~
./template.h:19:39: note: in instantiation of member function 'vector<3, Dummy>::operator+=' requested here
        case FunctionEnum::Add:   vec1+=vec2;
                                      ^
main.cpp:5:5: note: in instantiation of function template specialization 'foo<FunctionEnum::Dummy>' requested here
    foo<FunctionEnum::Dummy>();
    ^
In file included from main.cpp:1:
In file included from ./template.h:3:
In file included from ./vector.h:4:
./vector_imp.hpp:8:28: error: type 'const vector<3, Dummy>' does not provide a subscript operator
        member_array[i] += other[i];
                           ^~~~~ ~
./template.h:19:39: note: in instantiation of member function 'vector<3, Dummy>::operator+=' requested here
        case FunctionEnum::Add:   vec1+=vec2;
                                      ^
main.cpp:6:5: note: in instantiation of function template specialization 'foo<FunctionEnum::Add>' requested here
    foo<FunctionEnum::Add>();
    ^
2 errors generated.
```

Basically, there are **two actual errors** reported by clang, and the other locations are just notes, helpfully pointing to the error *causes*.

Now, here is what the Flycheck error list reports:

![flycheck](https://user-images.githubusercontent.com/340129/47443449-9c3b0980-d7b4-11e8-93cf-555c2b468e9f.png)

Flycheck finds **8 errors** and 2 info diagnostics.  What we would like to see instead is **2 errors** and **4 info**, each info corresponding to the causes of the 2 errors.  In particular, the top 6 errors reported by Flycheck are basically noise (and this noise can get quite loud, as your first post shows).

I've sent #1513 to fix it.

**Comment by nerrons** [comment] 2019-02-08 03:25
Hi, I'm wondering when can this improvement be merged? It would be really nice to have it since I use C quite a lot.

**Comment by fmdkdd** [comment] 2019-02-11 15:29
@nerrons Had some trouble with our CI, but it's finally merged.  Thanks for the reminder!

**Closed** 2019-02-11 15:29 UTC
