### ISSUE TITLE
suspicious state from syntax checker: ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by pankajbhanu** [flycheck/flycheck#994] opened 2016-06-21 13:47 UTC
I am getting this error on every edit made to a python file

i am using the following packages
flake8==2.5.4
flake8-blind-except==0.1.0
flake8-debugger==1.4.0
flake8-docstrings==0.2.5
flake8-isort==1.2
flake8-quotes==0.2.4

Checker definition probably flawed.
Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output: Traceback (most recent call last):
  File "/home/pankaj/.pyenv/versions/3.4.3/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pycodestyle.py", line 1877, in check_files
    runner(path)
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8_debugger.py", line 21, in run
    noqa = get_noqa_lines(self.filename)
  File "/home/pankaj/.pyenv/versions/3.4.3/lib/python3.4/site-packages/flake8_debugger.py", line 33, in get_noqa_lines
    tokens = tokenize.generate_tokens(lambda L=iter(code): next(L))
ValueError: I/O operation on closed file.

I tried removing each and every package one by one. couldn't catch any suspect. BTW the package versions are generated according to https://github.com/sloria/cookiecutter-flask

**Comment by lunaryorn** [comment] 2016-06-21 14:11
@pankajbhanu We pass the buffer contents to flake8 on standard input, and one or more of the flake8 plugins you've installed doesn't handle that—according to the stack trace it's pycodestyle.  We've seen that before with other plugins, and unfortunately there's little we can do.

You need to figure out which plugins break, and report upstream bugs.

To reproduce the issue on the terminal outside of Flycheck just use `flake8 - < my_python_file.py` instead of `flake8 my_python_file.py`.

I'm closing this issue because it's not strictly a problem with Flycheck.

**Closed by lunaryorn** 2016-06-21 14:11 UTC

**Comment by pankajbhanu** [comment] 2016-06-24 11:20
i figured out the plugin causing errors in pylint. After removing it the output of flake8 - < file.py and flake8 file.py do match.

But now when i open my project in emacs flycheck throws an error
`Flymake : configuration error has occurred while running (epylint app_flymake.py). Flymake will be switched off.`

**Comment by cpitclaudel** [comment] 2016-06-24 12:38
This is a Flymake error, not flycheck, right?

**Comment by lunaryorn** [comment] 2016-06-24 13:03
@cpitclaudel Indeed, it is.
