### ISSUE TITLE
Variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by EndlessDex** [flycheck/flycheck#1457] opened 2018-05-06 01:19 UTC
I'm attempting to set up `Flycheck version: 32snapshot (package: 20180422.2106)` in `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)` on `Ubuntu 18.04 LTS`.

Whenever I run flycheck I get `Error while checking syntax automatically: (error "Variable binding depth exceeds max-specpdl-size")`. I removed everything else from my config. Now it is just:

```
(package-initialize)

(require 'use-package)

(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
```
Running `M-x toggle-debug-on-error` and `M-x flycheck-buffer` on a blank buffer yields this backtrace:
```
Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  signal(error ("Variable binding depth exceeds max-specpdl-size"))
  flycheck-buffer()
  funcall-interactively(flycheck-buffer)
  #<subr call-interactively>(flycheck-buffer record nil)
  apply(#<subr call-interactively> flycheck-buffer (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> flycheck-buffer record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (flycheck-buffer record nil))
  call-interactively(flycheck-buffer record nil)
  command-execute(flycheck-buffer record)
  execute-extended-command(nil "flycheck-buffer" "flycheck-bu")
  funcall-interactively(execute-extended-command nil "flycheck-buffer" "flycheck-bu")
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by cpitclaudel** [comment] 2018-05-06 01:45
Thanks for the report ! And sorry for the trouble.  Please try to get rid of use-package, too -- you can just use `(require 'flycheck)`.  Also, it seems that you still have ido enabled?

**Comment by EndlessDex** [comment] 2018-05-06 04:31
Command sequence:
```
emacs -Q
M-x package-initialize
M-x global-flycheck-mode
M-x toggle-debug-on-error
M-x flycheck-buffer
---------------------------------------------------
Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  signal(error ("Variable binding depth exceeds max-specpdl-size"))
  flycheck-buffer()
  funcall-interactively(flycheck-buffer)
  #<subr call-interactively>(flycheck-buffer record nil)
  apply(#<subr call-interactively> flycheck-buffer (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> flycheck-buffer record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (flycheck-buffer record nil))
  call-interactively(flycheck-buffer record nil)
  command-execute(flycheck-buffer record)
  execute-extended-command(nil "flycheck-buffer" "flycheck-b")
  funcall-interactively(execute-extended-command nil "flycheck-buffer" "flycheck-b")
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Also:
```
emacs -Q
M-x package-initialize
M-x toggle-debug-on-error
M-x global-flycheck-mode
--------------------------------------------
Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  signal(error ("Variable binding depth exceeds max-specpdl-size"))
  flycheck-buffer()
  flycheck-buffer-automatically()
  flycheck-perform-deferred-syntax-check()
```

I don't know why there is an ido statement in the original version. It shouldn't be active. The second command sequence shows the same issue with no middle-man code.

**Comment by cpitclaudel** [comment] 2018-05-09 00:07
Thanks for testing.  This is quite surprising.
Can you say more about the way you install the package? Just MELPA? And how did you revert to v31?

**Comment by EndlessDex** [comment] 2018-05-09 01:03
I think the package was originally installed as a dependency of [elpy](https://github.com/jorgenschaefer/elpy), which I installed via `(use-package elpy)`. I remember seeing flycheck code downloading/compiling after adding elpy. I later added `(use-package flycheck)` in order to enable it for all modes and that is when I first noticed the problem (it errored out trying to parse my `.config`.

As for the versioning, I was originally using `http://melpa.org/packages/`. When I couldn't solve the problem, I deleted the flycheck folder and forced a reinstall. The problem persisted. I deleted teh file again and switched to `http://stable.melpa.org/packages/`. This fixed the error.

Have you been able to duplicate the bug?

**Comment by EndlessDex** [comment] 2018-05-09 01:03
[](url)

**Comment by cpitclaudel** [comment] 2018-05-09 20:58
> Have you been able to duplicate the bug?

No, unfortunately.  I did the following:

- Created a Vagrantfile in a new folder:

    ```
    Vagrant.configure("2") do |config|
      config.vm.box = "ubuntu/bionic64"
    end
    ```

- Initialized with `vagrant up` and logged in with `vagrant ssh`.

- Installed emacs 25.2.2 with `sudo apt install emacs`

- Created a new `.emacs` with these contents:

    ```
    (require 'package)
    (load-theme 'tango-dark t)

    (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                        (not (gnutls-available-p))))
           (proto (if no-ssl "http" "https")))
      ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
      (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
      ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
      (when (< emacs-major-version 24)
        ;; For important compatibility libraries like cl-lib
        (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))

    (package-initialize)
    ```

- Installed flycheck with `M-x list-packages`, `I`, `x`, `yes` and enabled it with `M-x global-flycheck-mode`

- Opened a new elisp file `test.el`, typed `asd`, and waited for a second for underlines to appear.

Underlines appeared under `asd` with the expected warning.
That was using the same versions of Ubuntu, Emacs, and Flycheck as you are, so I'm inclined to blame your site-lisp folder.  Do you have any emacs config besides your .emacs?  Can you try the following to get a clean Emacs to reproduce the problem in?

```
mkdir -p /tmp/sandbox
emacs -Q \
    --eval '(setq user-emacs-directory "/tmp/sandbox")' \
    -l package \
    --eval "(add-to-list 'package-archives '(\"gnu\" . \"http://elpa.gnu.org/packages/\") t)" \
    --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
    --eval "(package-refresh-contents)" \
    --eval "(package-initialize)" \
    --eval "(package-install 'flycheck)"
```

**Comment by jamessral** [comment] 2018-06-15 15:08
I am often getting the same error with my config, but I can't reproduce it with the steps you have here. I'm using version 26.1 . Invoking `(global-flycheck-mode)` with use-package causes me issues as well.

**Comment by fmdkdd** [comment] 2018-06-15 15:20
@jamessral If you can outline reproducing steps, that would help us tremendously to pinpoint the issue.

**Comment by cpitclaudel** [comment] 2018-06-15 15:21
@jamessral The usual way to diagnose this is to comment stuff out from your .emacs little by little, until you isolate the minimum needed to reproduce the issue.

**Comment by cpitclaudel** [comment] 2018-06-15 15:30
Got it, thanks :)

**Comment by cpitclaudel** [comment] 2020-03-19 22:35
I'm unable to reproduce this, so I'll close it for no.  If you can find a repro, please do let me know by reopening this bug.

**Closed by cpitclaudel** 2020-03-19 22:35 UTC
Labels: component: core, kind: bug, status: cannot reproduce
