### ISSUE TITLE
Import error of flycheck with pylint

### ISSUE THREAD

**Issue by arctanx0** [flycheck/flycheck#1219] opened 2017-02-26 07:29 UTC
My project structure is
```
cn_vocabulary/
    __init__.py
    utils/
        __init__.py
        scanner.py
        settings.py
```
When i wrote `from .settings import db_client` in `utils/__init__.py`, i got this error
![image](https://cloud.githubusercontent.com/assets/7189225/23337901/00c02706-fc37-11e6-98ce-5a7d3317ecc7.png)

> Unable to import cn_vocabulary.utils.flycheck___init__.settings

I don't know what is `flycheck___init__`

Verify setup:
![image](https://cloud.githubusercontent.com/assets/7189225/23337896/9a98805e-fc36-11e6-9d95-c3faa31fd3a7.png)

**Comment by fmdkdd** [comment] 2017-02-26 18:19
So, in order to check your files without saving them, Flycheck create temporary files.  Usually, these files are created under `/tmp` to avoid interfering with your folders.  For `python-pylint`, the temporary files are created in the same directory as the file your are editing, with a prefix of `flycheck-temp-prefix`.  Hence, since you are editing `__init__.py`, Flycheck is saving the contents of the buffer into `flycheck__init__.py`.

Then, since you are using the relative import `.settings`, pylint tries to find a `settings.py` in the current folder, but for some reason fails.  It may be because `pylint` is confused by this extra `flycheck__init__.py` file, and an empty `__init__.py`.  I don't know enough Python to be sure, but I would suggest to just save your `__init__.py` as a workaround.

A permanent solution would be to run the checker only on save; but I'm not sure it's worth it if the issue only happens for `__init__.py` files.

**Comment by arctanx0** [comment] 2017-02-27 05:48
@fmdkdd 

I saved `__init__.py`, but the error is still there. Also, I made an experiment shows that `pylint` wouldn't confuse such files(`f__init__.py` , `__init__.py`) when checking `import` statements. 

In addition, I type `C-c ! C-c` and run `pylint`,  the output said no error in this file. Maybe it is `flycheck`'s bug?

**Comment by fmdkdd** [comment] 2017-02-27 11:42
@arctanx0 I managed to reproduce your initial report, but cannot reproduce your latest comment.

I recreated your project structure with empty files, save for `utils/__init__py` which contains only the two lines from your screenshot.

First, of all, the output of `flycheck-compile` is misleading here:
```
pylint -r n --output-format text --msg-template \{path\}\:\{line\}\:\{column\}\:\{C\}\:\{symbol\}\:\{msg\} /tmp/cn_vocabulary/utils/__init__.py
```
You can see it does not insert the `flycheck` prefix for the filename, so `flycheck-compile` does not faithfully represent the command Flycheck will invoke automatically.  Also, the above pylint command outputs:
```
No config file found, using default configuration
************* Module cn_vocabulary.utils
__init__.py:1:0:C:missing-docstring:Missing module docstring
__init__.py:3:0:E:no-name-in-module:No name 'db_client' in module 'cn_vocabulary.utils.settings'
```
which is what we want.

But, if I `cp __init__.py flycheck__init__.py` and run
```
pylint -r n --output-format text --msg-template \{path\}\:\{line\}\:\{column\}\:\{C\}\:\{symbol\}\:\{msg\} /tmp/cn_vocabulary/utils/flycheck__init__.py
```
I do get all the errors that Flycheck reports:
```
************* Module cn_vocabulary.utils.flycheck__init__
flycheck__init__.py:1:0:C:missing-docstring:Missing module docstring
flycheck__init__.py:3:0:E:import-error:Unable to import 'cn_vocabulary.utils.flycheck__init__.settings'
************* Module cn_vocabulary.utils
__init__.py:1:0:C:missing-docstring:Missing module docstring
__init__.py:3:0:E:no-name-in-module:No name 'db_client' in module 'cn_vocabulary.utils.settings'
```

But if I `mv flycheck__init__.py flycheck.py`, and run pylint on that file, I get:
```
************* Module cn_vocabulary.utils.flycheck
flycheck.py:1:0:C:missing-docstring:Missing module docstring
flycheck.py:3:0:E:no-name-in-module:No name 'db_client' in module 'cn_vocabulary.utils.settings'
flycheck.py:3:0:W:unused-import:Unused db_client imported from settings
```

So it seems pylint is treating `flycheck__init__` (and any file containing `__init__`) as a separate module from `utils`, hence the confusion.

At this point, I don't know enough Python or pylint to decide whether that's a bug in pylint.  Should any file containing `__init__` be treated as a module root?  You might want to check with pylint developers to know.

On Flycheck's side we could stop using temporary files for pylint, but that would mean checking only on file save.

**Comment by arctanx0** [comment] 2017-02-27 16:06
@fmdkdd 
Thanks for your patience, now I know how `flycheck` check my file.
However, when I saved `__init__.py`, there is no `flycheck___init__.py` anymore, right?  but the error is still there.

I even modify my spacemacs config file to make sure that check the file after it was saved.
```elisp
(defun set-virtualenv-dir (path)
  "Prompt user to enter the virtualenv directory."
  (interactive
   (list
    (read-file-name "Set virtualenv directory:")))
  (flycheck-set-checker-executable 'python-pylint (concat (file-name-as-directory path) "bin/pylint"))
  (pyvenv-activate path)
  (message "ok."))

(setq flycheck-check-syntax-automatically '(mode-enabled save))
(add-hook 'python-mode-hook #'flycheck-mode)
```

**Comment by fmdkdd** [comment] 2017-02-27 16:30
@arctanx0 The file `flycheck___init__.py` is temporary, so it will only be created when Flycheck is running a syntax check for your buffer.  After that, the file is deleted.  You shouldn't be able to see it.

The error will happen as long as `pylint` is confused by this temporary file, or Flycheck is modified to not create temporary files for `pylint`.  For the first solution, check with upstream.

For the second, I was not suggesting that you modify `flycheck-check-syntax-automatically`; sorry for the misunderstanding.  Rather, I was referring to the syntax checker definition in `flycheck.el` itself.  Even if you modify `flycheck-check-syntax-automatically` as you did above, Flycheck will still use temporary files for pylint, because that's how the checker is defined.

Instead, if we define the checker as:
```elisp
(flycheck-define-checker python-pylint
  "A Python syntax and style checker using Pylint.

This syntax checker requires Pylint 1.0 or newer.

See URL `https://www.pylint.org/'."
  ;; -r n disables the scoring report
  :command ("pylint" "-r" "n"
            "--output-format" "text"
            "--msg-template"
            (eval (if flycheck-pylint-use-symbolic-id
                      "{path}:{line}:{column}:{C}:{symbol}:{msg}"
                    "{path}:{line}:{column}:{C}:{msg_id}:{msg}"))
            (config-file "--rcfile" flycheck-pylintrc)
            ;; Need `source-inplace' for relative imports (e.g. `from .foo
            ;; import bar'), see https://github.com/flycheck/flycheck/issues/280
            source-original)            ;; CHANGE: don't create temporary files
  :error-filter
  (lambda (errors)
    (flycheck-sanitize-errors (flycheck-increment-error-columns errors)))
  :error-patterns
  ((error line-start (file-name) ":" line ":" column ":"
          (or "E" "F") ":"
          (id (one-or-more (not (any ":")))) ":"
          (message) line-end)
   (warning line-start (file-name) ":" line ":" column ":"
            (or "W" "R") ":"
            (id (one-or-more (not (any ":")))) ":"
            (message) line-end)
   (info line-start (file-name) ":" line ":" column ":"
         "C:" (id (one-or-more (not (any ":")))) ":"
         (message) line-end))
  :modes python-mode
  :predicate flycheck-buffer-saved-p)  ;; CHANGE: run the checker only on save
```
I've made two simple modifications to the definitions included in `flycheck.el`; they are highlighted with `CHANGE:`.  If you add the above to your config, the error should disappear.  But, you will only get errors when saving the file.  No need to modify `flycheck-check-syntax-automatically`, as the way you have set it,  the variable will affect all Flycheck checkers, not just `pylint`.

We could merge this change to Flycheck, but I still do not know if `pylint`'s behavior is correct.

**Comment by arctanx0** [comment] 2017-02-28 05:03
Yes, it's good now. Thanks for your clear explanation.

I also try `fly___init__.py` with [flake8](http://flake8.pycqa.org/en/latest/), the output is correct. 

So, I don't think `pylint`'s behavior is correct, I will initiate an issue for this problem in `pylint`.

**Comment by fmdkdd** [comment] 2017-02-28 09:25
Glad it works for you :)

Let us know how the pylint issue works out.  In the mean time, I will close this bug.  Feel free to reopen if it turns out we need to fix something in Flycheck.

**Closed by fmdkdd** 2017-02-28 09:25 UTC

**Comment by arctanx0** [comment] 2017-03-01 02:07
PyCQA/pylint/issues/1348

**Comment by fmdkdd** [comment] 2017-03-01 11:36
@arctanx0 Great!
