### ISSUE TITLE
A global/per directory list of errors

### ISSUE THREAD

**Issue by gdkrmr** [flycheck/flycheck#1268] opened 2017-06-23 09:28 UTC
Some checkers can check directories/packages and therefore return errors for more than one file.
It would be really useful to collect these errors in one buffer and jump across files. Then there could also be something like `flycheck-directory` as an analog to `flycheck-buffer`.

**Comment by gdkrmr** [comment] 2017-06-23 09:30
there could also be a projectile integration

**Comment by fmdkdd** [comment] 2017-06-23 09:46
That's an often-requested feature (#829).  I think it's a significant departure from the way flycheck is currently set up.  #1191 was a step in this direction, but as everything, time from volunteers is the main ingredient here.

I would gladly assist you if you wanted to submit a pull request for this feature, in any case ;)

**Comment by gdkrmr** [comment] 2017-06-23 11:16
I did a quick search and did not find #829 I could have guessed that this would be a popular request, sorry for the duplicate.

**Comment by fmdkdd** [comment] 2017-06-23 12:37
Don't worry.  Actually, #966 was the one I had in mind.

**Comment by fmdkdd** [comment] 2017-07-17 09:30
Duplicate of #966.

**Closed by fmdkdd** 2017-07-17 09:30 UTC
Labels: duplicate, error list, feature request
