### ISSUE TITLE
Error installing on emacs 24.4

### ISSUE THREAD

**Issue by rvandegrift** [flycheck/flycheck#724] opened 2015-08-13 17:35 UTC
When I try to install flycheck from melpa, emacs 24.4 replies: "Package `emacs-24.3' is unavailable".

```sh
$ emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by lunaryorn** [comment] 2015-08-13 17:43
Duplicate of #130, closing.

**Comment by lunaryorn** [comment] 2015-08-13 17:43
Please remove legacy copies of package.el from your `load-path`.

**Closed by lunaryorn** 2015-08-13 17:43 UTC
